import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
import {createObserver,Budget,json,sha256} from '../tools/arm-validation/core.mjs';
import {encodeFrame,CAMERA,CAMERA_SHA256,CAPTURE_POLICY} from '../tools/arm-validation/capture.mjs';
import {prepareGeometryBody,modalPositions,attachmentMap,geometryMapper} from '../tools/arm-validation/geometry.mjs';
import {minimizeNewton} from '../web/anatomical-newton.mjs';
const pinned=p=>execFileSync('git',['show','0b18a4146768ab6a49cb2febdea696bf0c073434:'+p],{maxBuffer:8000000}).toString();
const reference=JSON.parse(execFileSync('git',['show','0b83819ad3fdaed7405c6bbe617bc01640eef914:education/data/anatomical-arm-v1/generated/arm-reference.json'],{maxBuffer:8000000}));
test('capture frame is detached exact little-endian coordinates, checksummed and bounded',()=>{
 const x=Float64Array.from({length:460},(_,i)=>i/10000),before=Array.from(x),frame=encodeFrame({status:'PROVISIONAL_NEWTON_ITERATE',physicalMotionAccepted:false},x),payload=frame.subarray(36);assert.equal(frame.readUInt32BE(0),payload.length);assert.equal(frame.subarray(4,36).toString('hex'),sha256(payload));const row=JSON.parse(payload),raw=Buffer.from(row.coordinatesFloat64LE,'base64');x.fill(0);assert.deepEqual(Array.from({length:460},(_,i)=>raw.readDoubleLE(i*8)),before);assert.equal(row.coordinatesSHA256,sha256(raw));assert.ok(frame.length<8192);assert.throws(()=>encodeFrame({},[0]),/coordinates/);assert.throws(()=>encodeFrame({},Array(460).fill(Infinity)),/coordinates/);assert.throws(()=>encodeFrame({large:'x'.repeat(8192)},before),/ceiling/);
});
test('observer on/off preserves synthetic Newton decisions, objective counts, coordinates and input alias',()=>{
 function run(enabled){let evaluations=0;const rows=[],limits={attempts:1,configurationEntries:100,muscleMaterial:0,tendonMaterial:0,materialTensor:0,hessianProducts:1000};const budget=new Budget(limits),capture=enabled?{snapshot(kind,a,x,meta){rows.push({kind,a,x:Array.from(x),meta});}}:null,obs=createObserver(budget,()=>{},4194304,capture),input={coordinatesM:Array(460).fill(.1),timeS:0,effort:.04},before=json(input);
 const arm={parameters:{stepS:.01}};const result=obs.attempt(arm,input,{h:.01},()=>{const r=minimizeNewton(y=>{evaluations++;return {energy:.5*y.reduce((s,v)=>s+v*v,0),gradient:Float64Array.from(y),diagonal:Float64Array.from(y,()=>1),hessianVector:v=>Float64Array.from(v),fullCoordinates:Float64Array.from(y)};},Float64Array.from(input.coordinatesM),{tolerance:1e-8,maxIterations:10,cgMaxIterations:10,onIteration:row=>obs.progress(row)});return {accepted:r.converged,state:{...input,coordinatesM:Array.from(r.fullCoordinates),timeS:.01},receipt:{trace:r.trace,evaluations:r.evaluations,hessianProducts:r.hessianProducts}};});assert.equal(json(input),before);return {result,evaluations,budget:budget.snapshot(),rows};}
 const off=run(false),on=run(true);assert.deepEqual(on.result,off.result);assert.equal(on.evaluations,off.evaluations);assert.deepEqual(on.budget,off.budget);assert.equal(on.rows[0].kind,'BEGIN');assert.equal(on.rows.at(-1).kind,'STEP_CANDIDATE');assert.ok(on.rows.some(r=>r.kind==='NEWTON_ITERATE'));on.rows[0].x.fill(5);assert.equal(on.result.state.coordinatesM[0],0);
});
test('pure body preparation and modal positions match exact pinned expressions for all seven bodies',()=>{
 const source=pinned('education/web/anatomical-modal.mjs'),segment=source.slice(source.indexOf(' const rings='),source.indexOf(' const points=')),position=source.match(/export function modalPositions[^\n]+/)[0].replace('export ','');const referencePrepare=vm.runInNewContext(`const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),sub=(a,b)=>a.map((v,i)=>v-b[i]);(m)=>{${segment}return {source:m,nodeModes};}`),referencePosition=vm.runInNewContext(position+';modalPositions');
 for(const m of reference.muscles){const b=prepareGeometryBody(m),expected=referencePrepare(m);assert.equal(json(b.nodeModes),json(expected.nodeModes));for(const x of [Array(63).fill(0),Array.from({length:63},(_,i)=>Math.sin(i)*.002)])assert.equal(json(modalPositions(b,x)),json(referencePosition(expected,x)));assert.deepEqual(modalPositions(b,Array(63).fill(0)),m.nodes_m);}
});
test('pure Rodrigues bone map matches exact pinned function including bind pose and moving flags',()=>{
 const source=pinned('education/web/anatomical-transfer.mjs'),start=source.indexOf('export function attachmentMap'),end=source.indexOf('export function tendonTransfer'),body=source.slice(start,end).replace('export ','');const expected=vm.runInNewContext(`const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];${body};attachmentMap`);
 for(const q of [reference.frame.atlas_bind_angle_rad,-.1,.7])for(const moving of [false,true])for(const b of reference.bones)for(const x of b.vertices_m)assert.equal(json(attachmentMap(x,reference.frame,q,{moving})),json(expected(x,reference.frame,q,{moving})));
 const x=Array(460).fill(0);x[459]=.1*reference.frame.atlas_bind_angle_rad;const map=geometryMapper(reference),r=map(x);assert.deepEqual(r.muscles,reference.muscles.map(m=>m.nodes_m));assert.deepEqual(r.bones,reference.bones.map(b=>b.vertices_m));assert.deepEqual(r.omittedCoordinateIndices,Array.from({length:18},(_,i)=>441+i));
});
test('renderer imports only Three/pure geometry; camera and physical operator remain pinned',()=>{
 for(const p of ['geometry.mjs','render-browser.mjs']){const text=fs.readFileSync(new URL('../tools/arm-validation/'+p,import.meta.url),'utf8');assert.ok(!/\b(?:prepareModalBody|prepareAnatomicalArm|evaluateApparatus|muscleMaterial|tendonSegment)\s*\(/.test(text));const imports=[...text.matchAll(/from\s*['"]([^'"]+)['"]/g)].map(m=>m[1]);assert.deepEqual(imports,p==='geometry.mjs'?[]:['three','./geometry.mjs']);}
 assert.equal(CAMERA_SHA256,sha256(json(CAMERA)));assert.equal(CAMERA_SHA256,'428df4283bc6f4506f28a1fd1ceaeea2031e8ed9942e25d112a6820c4973c96e');assert.equal(CAPTURE_POLICY.maxFrames,34);
 const closure=JSON.parse(fs.readFileSync('/tmp/kenoma-arm-independent-substeps-proposal-20261009/reviewed-unrun-manifest.json'));for(const [p,item] of Object.entries(closure.modules))assert.equal(sha256(pinned(p)),item.sha256);
});
