import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';
import {ShellEvidenceStore,RuntimeLimits,assembleShellStage,compareShellStages,RECONSTRUCTION_GATES} from '../tools/element247-shell-runtime.mjs';
import {SHELL_RECIPES,shellRule,SHELL_BUDGET} from '../tools/element247-shell-protocol.mjs';
import {referencePoint} from '../tools/isolated-collapse-components.mjs';
const dirs=()=>fs.mkdtempSync(path.join(os.tmpdir(),'kenoma-shell-runtime-'));
const baseNodes=[[0,0,0],[1,0,0],[0,1,0],[0,0,1],[.5,0,0],[0,.5,0],[0,0,.5],[.5,.5,0],[.5,0,.5],[0,.5,.5]];
const fixture={nodes_m:[...baseNodes,...Array.from({length:575},()=>[2,2,2])],elements_ten_node:[[0,1,2,3,4,5,6,7,8,9]],reference_fibres:[[0,0,1]]};
const tensor=k=>[k,0,0,0,k,0,0,0,k],synthetic=()=>({actual:{J:1,P:tensor(10),energy:{matrix:1,volume:2,passiveFiber:3,activePotential:4}},stresses:{matrix:tensor(1),volume:tensor(2),passiveFiber:tensor(3),activePotential:tensor(4)}});
const direction=fixture.nodes_m.map((_,i)=>[i===0?.001:0,0,0]);
function setup(recipe=SHELL_RECIPES[0],options={}){const root=dirs(),store=new ShellEvidenceStore(root,{maximumBytes:8*1024**2}),limits=new RuntimeLimits({plannedCalls:recipe.points,maximumCalls:recipe.points,...options}),context={state:'fixture',completedShells:[]};return {root,store,limits,context,recipe,points:[...shellRule(recipe)],source:fixture,element:0,positions:fixture.nodes_m,direction};}
function firstShellWeights(s){const ps=s.points.filter(p=>p.shell==='s1'),bytes=Buffer.alloc(ps.length*8);ps.forEach((p,i)=>bytes.writeDoubleLE(referencePoint(fixture,0,p.L,p.weight).weightM3,i*8));return bytes;}
test('complete synthetic actual shell path retains originals, independent total and all585 reactions',()=>{
 const s=setup(),out=assembleShellStage({...s,materialCallback:synthetic});s.limits.finish();assert.equal(s.limits.actual,1344);assert.equal(s.limits.completed,1344);assert.equal(out.originalShells.length,21);assert.equal(out.localShellFiles.length,21);assert.equal(fs.readdirSync(s.store.directory).length,42);assert.equal(out.physicalWeights.length,1344*8);assert.ok(Math.abs(out.energiesJ.total-10/6)<1e-13);assert.equal(out.nodalGradientsN.total.length,585);assert.deepEqual(out.reconstruction.gates,{forceN:1e-8,energyJ:1e-9});assert.equal(out.reconstruction.elementToGlobal.all585Nodes,true);assert.equal(out.reconstruction.elementToGlobal.maximumForceDifferenceN,0);assert.ok(out.nodalGradientsN.total.slice(10).every(v=>v.every(x=>x===0)));assert.ok(out.nodalGradientsN.total[4][1]<0);assert.ok(out.localGradientsN.total[4][1]<0);
 // Independent affine constant-stress P2 oracle: vertices integrate to zero,
 // edge01 has gradients(0,-1,-1), volume1/6; no material law was evaluated.
 assert.ok(Math.abs(out.nodalGradientsN.total[4][1]+10/6)<1e-13);assert.ok(Math.abs(out.nodalGradientsN.total[4][2]+10/6)<1e-13);for(const v of out.nodalGradientsN.total.slice(0,4))assert.ok(v.every(x=>Math.abs(x)<1e-13));
});
test('shell-to-element and global comparison checks reject a damaged nonincident node and missing original',()=>{
 const s=setup(),A=assembleShellStage({...s,materialCallback:synthetic}),B=structuredClone(A);B.nodalGradientsN.volume[584][2]=1e-4;assert.throws(()=>compareShellStages(A,B,direction,fixture.elements_ten_node[0],5.492029235357012e-7),/grouping/);const short=structuredClone(A);short.comparisonShells.pop();assert.throws(()=>compareShellStages(A,short,direction,fixture.elements_ten_node[0],5.492029235357012e-7),/inventory/);
});
test('component total reconstruction refuses damage before a completed stage can be retained',()=>{
 const s=setup();let caught;try{assembleShellStage({...s,materialCallback:()=>({...synthetic(),actual:{...synthetic().actual,P:tensor(11)}})});}catch(e){caught=e;}assert.ok(caught);assert.match(caught.message,/reconstruction/);assert.equal(s.limits.actual,64);assert.equal(s.limits.completed,64);assert.equal(s.context.completedShells.length,0);assert.equal(s.context.partialShell.completedPoints,64);assert.equal(s.context.physicalWeightEvidenceComplete,true);assert.equal(s.context.retainedWeightFile,'C44-fixture-s1-partial-weights.f64le');assert.deepEqual(fs.readFileSync(path.join(s.store.directory,s.context.retainedWeightFile)),firstShellWeights(s));s.store.failure(caught,s.context,s.limits);const failure=JSON.parse(fs.readFileSync(path.join(s.store.directory,'incomplete-receipt.json')));assert.equal(failure.context.partialShell.localGradientsN.total.length,10);assert.equal(failure.context.physicalWeightEvidenceComplete,true);assert.equal(failure.runtime.actualConstitutiveCallbacks,64);
});
test('combined output includes external log growth and preserves incomplete shell evidence',()=>{
 const s=setup();fs.writeFileSync(path.join(s.root,'execute.log'),Buffer.alloc(6*1024**2+1));assert.throws(()=>s.store.checkStorage('external-growth'),/STORAGE/);assert.equal(s.limits.actual,0);s.store.failure(Error('external log exceeded normal allowance'),s.context,s.limits);assert.ok(fs.existsSync(path.join(s.store.directory,'incomplete-receipt.json')));assert.throws(()=>new ShellEvidenceStore(s.root),/Preserve/);
});
test('throwing shell callback retains partial vectors and physical weights, counted once with no retry',()=>{
 const s=setup();let calls=0,caught;try{assembleShellStage({...s,materialCallback:()=>{if(++calls===3)throw Error('synthetic failure');return synthetic();}});}catch(e){caught=e;}assert.equal(s.limits.actual,3);assert.equal(s.limits.completed,2);assert.equal(calls,3);assert.equal(s.context.partialShell.completedPoints,2);assert.equal(s.context.partialShell.localGradientsN.total.length,10);assert.ok(fs.existsSync(path.join(s.store.directory,'C44-fixture-s1-partial-weights.f64le')));assert.equal(fs.statSync(path.join(s.store.directory,'C44-fixture-s1-partial-weights.f64le')).size,16);s.store.failure(caught,s.context,s.limits);assert.equal(JSON.parse(fs.readFileSync(path.join(s.store.directory,'incomplete-receipt.json'))).runtime.actualConstitutiveCallbacks,3);
});
test('post-assembly output refusal retains complete shell weights and vector in reserved evidence',()=>{
 const s=setup(),original=s.store.json.bind(s.store);s.store.json=(name,value,options)=>{if(name==='C44-fixture-s1-shell.json')throw Error('synthetic output refusal');return original(name,value,options);};let caught;try{assembleShellStage({...s,materialCallback:synthetic});}catch(e){caught=e;}assert.ok(caught);assert.equal(s.limits.actual,64);assert.equal(s.context.partialShell.completedPoints,64);assert.equal(s.context.partialShell.physicalWeightsComplete,true);assert.equal(fs.statSync(path.join(s.store.directory,'C44-fixture-s1-weights.f64le')).size,512);s.store.failure(caught,s.context,s.limits);assert.ok(fs.existsSync(path.join(s.store.directory,'incomplete-receipt.json')));
});
test('truncated and same-length damaged normal weight files cannot suppress verified emergency retention',()=>{
 for(const mode of ['truncated','same-length']){const s=setup(),write=s.store.write.bind(s.store);s.store.write=(name,data,options)=>{if(name==='C44-fixture-s1-weights.f64le'){const bad=mode==='truncated'?data.subarray(0,13):Buffer.from(data);if(mode==='same-length')bad[0]^=1;write(name,bad,options);throw Error(`synthetic ${mode} weight write`);}return write(name,data,options);};let caught;try{assembleShellStage({...s,materialCallback:synthetic});}catch(e){caught=e;}assert.ok(caught);assert.equal(s.limits.actual,64);assert.equal(s.context.normalWeightBytes,mode==='truncated'?13:512);assert.equal(s.context.physicalWeightEvidenceComplete,true);assert.equal(s.context.retainedWeightFile,'C44-fixture-s1-partial-weights.f64le');assert.deepEqual(fs.readFileSync(path.join(s.store.directory,s.context.retainedWeightFile)),firstShellWeights(s));assert.notDeepEqual(fs.readFileSync(path.join(s.store.directory,'C44-fixture-s1-weights.f64le')),firstShellWeights(s));s.store.failure(caught,s.context,s.limits);assert.equal(JSON.parse(fs.readFileSync(path.join(s.store.directory,'incomplete-receipt.json'))).context.physicalWeightEvidenceComplete,true);}
});
test('failed emergency weight write is explicit and never reported as complete persisted evidence',()=>{
 const s=setup(),write=s.store.write.bind(s.store);s.store.write=(name,data,options)=>{if(name.includes('weights.f64le'))throw Error('synthetic unavailable weight write');return write(name,data,options);};let caught;try{assembleShellStage({...s,materialCallback:synthetic});}catch(e){caught=e;}assert.ok(caught);assert.equal(s.context.partialShell.completedPoints,64);assert.equal(s.context.physicalWeightEvidenceComplete,false);assert.match(s.context.partialWeightWriteError,/unavailable/);assert.equal(s.context.retainedWeightFile,undefined);s.store.failure(caught,s.context,s.limits);assert.equal(JSON.parse(fs.readFileSync(path.join(s.store.directory,'incomplete-receipt.json'))).context.physicalWeightEvidenceComplete,false);
});
test('shell wall and RSS refusals preserve partial evidence at actual callback entry boundaries',()=>{
 for(const kind of ['wall','rss']){let now=0,rss=0;const recipe=SHELL_RECIPES[1],s=setup(recipe,{wallMs:10,rssBytes:10,now:()=>now,rss:()=>rss});let calls=0,caught;try{assembleShellStage({...s,materialCallback:()=>{calls++;if(kind==='wall'&&calls===2)now=10;if(kind==='rss'&&calls===125)rss=11;return synthetic();},onCheckpoint:()=>s.limits.check('shell-check')});}catch(e){caught=e;}assert.ok(caught);s.store.failure(caught,s.context,s.limits);assert.ok(s.limits.actual<=125);assert.equal(calls,s.limits.actual);assert.ok(fs.existsSync(path.join(s.store.directory,'incomplete-receipt.json')));}
});
test('frozen call/time/memory/output and reconstruction bounds precede all results',()=>{assert.deepEqual(RECONSTRUCTION_GATES,{forceN:1e-8,energyJ:1e-9});assert.equal(SHELL_BUDGET.plannedMaterialCalls,62438);assert.equal(SHELL_BUDGET.maximumMaterialCalls,62500);assert.equal(SHELL_BUDGET.maximumWallSeconds,180);assert.equal(SHELL_BUDGET.nodeHeapMiB,1024);assert.equal(SHELL_BUDGET.maximumRssBytes,2*1024**3);assert.equal(SHELL_BUDGET.maximumOutputBytes,64*1024**2);});
test('material CLI refuses missing authorization before invocation/output/material callbacks',()=>{
 const cwd=path.resolve(import.meta.dirname,'..'),auth=path.join(cwd,'research/element247-shell-execution-authorization-20261007.json'),out=path.join(cwd,'review/element247-shell-run-20261007');assert.equal(fs.existsSync(auth),false);assert.equal(fs.existsSync(out),false);assert.throws(()=>execFileSync(process.execPath,['--max-old-space-size=1024','tools/run-element247-shell.mjs','--execute'],{cwd,stdio:'pipe'}),e=>e.status!==0&&e.stderr.toString().includes('NO_MATERIAL_EXECUTION_AUTHORIZATION'));assert.equal(fs.existsSync(out),false);
});
