/** Constant injected callbacks and retained arithmetic only; zero specimen calls. */
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';
import {BUDGET,SCHEDULE,NORMALIZED_RECIPES,SECONDARY,CORNERS,recipe,regionRule,regionRow,constructStage,compareUnits,packPoints,normalizationKey,regionKey,ALL_TERMS} from '../tools/selective-fixed-patch-protocol.mjs';
import {shells} from '../tools/element247-shell-protocol.mjs';
import {RuntimeLimits,hashBytes} from '../tools/element247-shell-runtime.mjs';
import {PatchEvidenceStore,boundedJson,outputPlan} from '../tools/selective-fixed-patch-storage.mjs';
import {assembleStage} from '../tools/selective-fixed-patch-runtime.mjs';
import {loadInputs,baselineFor,assembleCandidate} from '../tools/selective-fixed-patch-inputs.mjs';
import {referencePoint} from '../tools/isolated-collapse-components.mjs';
const {source,arrays}=loadInputs();
const constant=()=>{const v=[2,-1,3,4,1,-2,5,-3,6];return {actual:{J:1,P:v.map(x=>10*x),energy:Object.fromEntries(ALL_TERMS.slice(0,-1).map((t,i)=>[t,7*(i+1)]))},stresses:Object.fromEntries(ALL_TERMS.slice(0,-1).map((t,i)=>[t,v.map(x=>(i+1)*x)]))};};
function fixture(rs){const directory=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'kenoma-selective-fixture-')),'run');fs.mkdirSync(directory);const store=new PatchEvidenceStore(directory),artifactHashes={},data={};for(const r of rs)for(const s of shells(r.depth)){const ps=[...regionRule(r,s)],p=packPoints(ps),w=Buffer.alloc(ps.length*8);ps.forEach((q,i)=>w.writeDoubleLE(referencePoint(source,r.element,q.L,q.weight).weightM3,i*8));for(const [n,b] of [[`${normalizationKey(r)}-${s.id}-points.f64le`,p],[`${regionKey(r,s.id)}-weights.f64le`,w]]){data[n]=b;artifactHashes[n]=hashBytes(b);}}const calls=rs.reduce((s,r)=>s+r.points,0),limits=new RuntimeLimits({plannedCalls:calls,maximumCalls:calls,wallMs:300000,rssBytes:2147483648});return {store,limits,context:{reusedPoints:0,completedRegions:[],partialRegion:null},preflight:{artifactHashes},readArtifact:n=>data[n]};}
test('closed schedule, all permutations and exact counts',()=>{assert.equal(SCHEDULE.reduce((n,r)=>n+2*r.points,0)-4000,497500);assert.equal(BUDGET.maximumMaterialCalls,497500);assert.equal(SCHEDULE.reduce((n,r)=>n+2*(r.depth+1),0),634);assert.equal(NORMALIZED_RECIPES.length,11);for(const [e,c] of Object.entries(CORNERS))assert.equal(source.elements_ten_node[e][c],92);assert.throws(()=>recipe(195,'C55'));assert.throws(()=>regionRule({...recipe(197,'C55'),corner:0},shells(20)[0]).next());});
test('nonzero producer to actual bounded JSON to constructor for all six mappings and247; full16 composite',()=>{
 const rs=[...SECONDARY.map(e=>recipe(e,'C55')),recipe(247,'F44')],f=fixture(rs),stages={};let calls=0;
 for(const r of rs){const stage=assembleStage({source,r,state:'control45',positions:arrays.positionsM.control45,direction:arrays.terminalDirectionM,...f,materialCallback:()=>{calls++;return constant();}});stages[`${r.element}-${r.id}`]=stage;assert.ok(stage.localGradientsN.total.flat().some(v=>v!==0));assert.ok(stage.energiesJ.total>0);const rows=shells(20).map(s=>JSON.parse(fs.readFileSync(path.join(f.store.directory,`control45-${regionKey(r,s.id)}-region.json`))));assert.deepEqual(constructStage(source,r,rows),stage);const damaged=structuredClone(rows);delete damaged[0].shell;assert.throws(()=>constructStage(source,r,damaged));const conflict=structuredClone(rows);conflict[0].id='s2';assert.throws(()=>constructStage(source,r,conflict));assert.throws(()=>constructStage(source,r,rows.slice(1)));}
 f.limits.finish();assert.equal(calls,57750);const q=assembleCandidate(source,'control45','Q0',stages,baselineFor(source,'control45'));assert.equal(q.localElements.length,16);assert.equal(q.hybridNodalGradientsN.total.length,585);assert.ok(q.hybridNodalGradientsN.total.some((v,n)=>arrays.heldNodeOrder.includes(n)&&v.some(x=>x!==0)));assert.equal(q.outsidePatchQualified,false);
});
test('unit triangle prevents cancellation and held-node differences count',()=>{const e=197,a={element:e,localGradientsN:Object.fromEntries(ALL_TERMS.map(t=>[t,Array.from({length:10},()=>[0,0,0])]))},b=structuredClone(a),c=structuredClone(a);for(const t of ALL_TERMS){b.localGradientsN[t][0][0]=2e-5;c.localGradientsN[t][0][0]=-2e-5;}const x=compareUnits(source,[{id:'one',a,b},{id:'two',a,b:c}],arrays.terminalDirectionM,2);assert.equal(x.terms.total.aggregateInfinityN,0);assert.equal(x.terms.total.unitTriangleInfinityN,4e-5);assert.equal(x.pass,false);assert.throws(()=>compareUnits(source,[{id:'one',a,b}],arrays.terminalDirectionM,2));const heldElement=source.elements_ten_node.findIndex(ids=>ids.some(n=>arrays.heldNodeOrder.includes(n))),i=source.elements_ten_node[heldElement].findIndex(n=>arrays.heldNodeOrder.includes(n)),ha={...a,element:heldElement},hb=structuredClone(ha);for(const t of ALL_TERMS)hb.localGradientsN[t][i][0]=2e-5;assert.equal(compareUnits(source,[{id:'held',a:ha,b:hb}],arrays.terminalDirectionM,1).pass,false);});
test('finite bounded encoding and closed filenames refuse oversize/nonfinite storage',()=>{const plan=outputPlan();assert.equal(plan.binaryBytes,12782000);assert.equal(plan.maximumCombinedBytes,48925104);assert.ok(plan.maximumCombinedBytes<BUDGET.maximumOutputBytes);assert.throws(()=>boundedJson({a:NaN},8192));assert.throws(()=>boundedJson({a:'x'.repeat(513)},8192));assert.throws(()=>boundedJson({a:1},2));const f=fixture([]);assert.throws(()=>f.store.write('arbitrary.json','{}'));assert.throws(()=>f.store.write('saved-arrays.json',Buffer.alloc(131073)));assert.throws(()=>f.store.write('197-C55-s1-weights.f64le',Buffer.alloc(8)));});
test('counted callback failure remains incomplete without retry',()=>{const limits=new RuntimeLimits({plannedCalls:2,maximumCalls:2});limits.beginBatch(2,'fixture');assert.throws(()=>limits.invoke(()=>{throw Error('synthetic law refusal');}));assert.equal(limits.actual,1);assert.equal(limits.completed,0);assert.throws(()=>limits.finish());});
test('truncated normal weights preserve current complete bytes and partial region',()=>{const r=recipe(197,'C55'),f=fixture([r]),write=f.store.write.bind(f.store);f.store.write=(name,data,options)=>{if(name==='197-C55-s1-weights.f64le'){fs.writeFileSync(path.join(f.store.directory,name),data.subarray(0,13));throw Error('synthetic truncated write');}return write(name,data,options);};assert.throws(()=>assembleStage({source,r,state:'control45',positions:arrays.positionsM.control45,direction:arrays.terminalDirectionM,...f,materialCallback:constant}),/truncated/);assert.equal(f.limits.actual,125);assert.equal(f.context.partialRegion.completedPoints,125);assert.equal(f.context.physicalWeightEvidenceComplete,true);assert.equal(fs.statSync(path.join(f.store.directory,'partial-weights.f64le')).size,1000);f.store.failure(Error('synthetic failure'),f.context,f.limits);assert.equal(JSON.parse(fs.readFileSync(path.join(f.store.directory,'incomplete-receipt.json'))).runtime.actualConstitutiveCallbacks,125);});
test('reference weight damage refuses reuse without replacement calls',()=>{const r=recipe(247,'F44'),f=fixture([r]),s=shells(20)[0],local={element:247,pointCount:2000,minimumSampleJ:1,energiesJ:Object.fromEntries(ALL_TERMS.map(t=>[t,1])),localGradientsN:Object.fromEntries(ALL_TERMS.map(t=>[t,Array.from({length:10},()=>[1,2,3])]))};f.preflight.artifactHashes['247-F44-s1-weights.f64le']='0'.repeat(64);assert.throws(()=>assembleStage({source,r,state:'terminal46',positions:arrays.positionsM.terminal46,direction:arrays.terminalDirectionM,...f,materialCallback:()=>{throw Error('must not call');},reusedRows:{s1:regionRow(local,r,s)}}));assert.equal(f.limits.actual,0);});
test('serialization preserves nonzero values and rejects contradictory chart identity',()=>{const r=recipe(200,'C55'),s=shells(20)[0],local={element:200,pointCount:125,minimumSampleJ:1,energiesJ:Object.fromEntries(ALL_TERMS.map(t=>[t,1])),localGradientsN:Object.fromEntries(ALL_TERMS.map(t=>[t,Array.from({length:10},()=>[1,2,3])]))};const row=regionRow(local,r,s);assert.deepEqual(JSON.parse(boundedJson(row,8192)),row);assert.throws(()=>regionRow({...local,comparisonShell:'core'},r,s));assert.throws(()=>regionRow({...local,shell:'s2'},r,s));});
