import pathlib,json,csv,hashlib,sys,datetime
ROOT=pathlib.Path('/tmp/Kenoma-fine-window-material-run/education');RUN=ROOT/'review/fine-window-run-20261007';OUT=ROOT/'review/fine-window-outcome-20261007'
assert not OUT.exists();OUT.mkdir();mat=RUN/'material';read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();completion=read(mat/'completion-receipt.json');public=read(RUN/'public-entry-exit.json');external=read(RUN/'external-exit.json');launcher=read(RUN/'launcher-exit.json');verifier=read(OUT.parent/'fine-window-verification-20261007.json')
assert public['publicEntryExitCode']==external['childExitCode']==launcher['launcherExitCode']==0;assert public['runId']==completion['runId'];assert public['elapsedMs']<7200000
comparisons=[];terms=[]
for cmeta in completion['comparisons']:
 state,a,b=cmeta['state'],cmeta['a'],cmeta['b'];quiet=a in ['D4','U4','D5'];name=f'{state}-'+('quiet-' if quiet else '')+f'{a}-{b}-comparison.json';c=read(mat/name);assert c['pass']==cmeta['pass']
 row={'state':state,'comparison':a+'/'+b,'required':c['required'],'pass':c['pass'],'globalPass':c['globalPass'],'forceSignedN':max(v['aggregateInfinityN'] for v in c['terms'].values()),'forceTriangleN':max(v['unitTriangleInfinityN'] for v in c['terms'].values()),'workSignedJ':max(v['aggregateDirectionalDifferenceJ'] for v in c['terms'].values()),'workTriangleJ':max(v['unitTriangleDirectionalDifferenceJ'] for v in c['terms'].values()),'failedTerms':[t for t,v in c['terms'].items() if not v['pass'] or (quiet and not v['allocatedPass']) or any(not group['metrics'][t]['pass'] for group in c.get('allocations',{}).values())],'allocationPasses':{k:v['pass'] for k,v in c.get('allocations',{}).items()},'artifact':name,'sha256':sha(mat/name)};comparisons.append(row)
 for t,v in c['terms'].items():
  record={'state':state,'comparison':a+'/'+b,'required':c['required'],'term':t,'globalPass':v['pass'],'signedN':v['aggregateInfinityN'],'triangleN':v['unitTriangleInfinityN'],'signedWorkJ':v['aggregateDirectionalDifferenceJ'],'triangleWorkJ':v['unitTriangleDirectionalDifferenceJ'],'forceGateN':v['forceGateN'],'workGateJ':v['workGateJ']}
  if quiet:record['allocatedPass']=v['allocatedPass'];record['allocatedForceN']=c['allocatedForceN'];record['allocatedWorkJ']=c['allocatedWorkJ']
  else:record['allocations']={k:v['metrics'][t] for k,v in c['allocations'].items()}
  terms.append(record)
files={str(p.relative_to(RUN)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(RUN.rglob('*')) if p.is_file()};inventory={'schema':1,'runId':completion['runId'],'sourceCommit':completion['sourceCommit'],'files':files,'bytes':sum(v['bytes'] for v in files.values()),'fileCount':len(files)};(OUT/'raw-inventory.json').write_text(json.dumps(inventory,indent=2)+'\n')
summary={'schema':1,'result':completion['result'],'runId':completion['runId'],'executionSourceCommit':completion['sourceCommit'],'runnerSourceCommit':completion['runnerSourceCommit'],'authorizationSha256':sha(ROOT/'research/fine-window-authorization-20261007.json'),'newCallbacks':completion['newCallbacks'],'sharedLogicalMeasurements':completion['sharedLogicalMeasurements'],'retainedAttribution':{'sameInvocationP4':480000,'historicalF44':80000,'historicalX44':80000,'historicalFailedTwoShellSubsetThroughF44':4000},'logicalRegions':completion['logicalRegions'],'newRegions':completion['newRegions'],'sharedRegions':completion['sharedRegions'],'comparisons':comparisons,'termMetrics':terms,'requiredPass':sum(c['required'] and c['pass'] for c in comparisons),'requiredFail':sum(c['required'] and not c['pass'] for c in comparisons),'informationalPass':sum(not c['required'] and c['pass'] for c in comparisons),'informationalFail':sum(not c['required'] and not c['pass'] for c in comparisons),'runtime':completion['runtime'],'externalExit':external,'launcherExit':launcher,'publicEntryExit':public,'verification':verifier,'combinedRawBytes':inventory['bytes'],'rawFileCount':len(files),'rawInventorySha256':sha(OUT/'raw-inventory.json'),'outsidePatchElements':236,'outsidePatchQualified':False,'anatomicalQualification':False,'originalResultCommit':completion['originalResultCommit'],'originalResult':completion['originalResult'],'originalTwoShellExecutionExit':completion['originalTwoShellExecutionExit'],'retryPerformed':False};(OUT/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
with (OUT/'comparisons.csv').open('x',newline='') as f:
 keys=['state','comparison','required','pass','globalPass','forceSignedN','forceTriangleN','workSignedJ','workTriangleJ','failedTerms','allocationPasses','artifact','sha256'];writer=csv.DictWriter(f,fieldnames=keys);writer.writeheader();writer.writerows(comparisons)
md=['# Frozen fine-window specimen outcome','',f"Result: **{completion['result']}**. Exactly one authorized invocation, run `{completion['runId']}`. No retry or additional material evaluation.",'',f"Operational/scalar verification: **{verifier['verdict']}**. Public, worker and child exits are0. All19,716,000 new callbacks reserved, entered and completed. 640,000 shared logical measurements remain separately attributed:480,000 same-invocation P4,80,000 historical F44 and80,000 historical X44; the4,000 failed-two-shell measurements remain attributed through immutable F44, not counted again as new calls.",'',f"Public-entry elapsed {public['elapsedMs']/1000:.6f}s. External measured peak child RSS {external['peakObservedChildRssBytes']}B. Combined raw output {inventory['bytes']}B across{len(files)}files. Frozen new caps:7200s,2GiB RSS,1GiB Node heap,512MiB combined output. Runtime and all terminal/resource/actual exit receipts are preserved.",'',f"Required comparisons: {summary['requiredPass']} PASS / {summary['requiredFail']} FAIL; informational comparisons: {summary['informationalPass']} PASS / {summary['informationalFail']} FAIL.",'','| Field | Comparison | Role | Verdict | Max force signed / triangle (N) | Max work signed / triangle (J) |','|---|---|---|---|---:|---:|']
for c in comparisons:md.append(f"| {c['state']} | {c['comparison']} | {'required' if c['required'] else 'informational'} | {'PASS' if c['pass'] else 'FAIL'} | {c['forceSignedN']:.8g} / {c['forceTriangleN']:.8g} | {c['workSignedJ']:.8g} / {c['workTriangleJ']:.8g} |")
md += ['','Verdicts include both unchanged global force/work gates and the separately allocated quiet/focus gates. Force/work maxima in this table range over all five terms; complete per-term/per-allocation metrics are in [summary.json](summary.json) and raw comparisons. The matched156-unit partition and all585 nodes include held reactions; common16 diagnostics remain supplementary. Quiet D4/D5, U4/U5 and D5/U5 witnesses are required retained evidence, not new specimen evaluations.','', 'S0/S1/S2 are primary angular2/4/8; I0/I1 are the separate affine tetrahedron family; S2/I1 is the finest cross-family check. S1/AR, S1/AH and S1/AC isolate radial, depth and chart changes. Informational S0/I0 and S1/I1 comparisons never replace a required gate.','', 'The original frozen38ae result, coarse Q0/Q1 failures and failed two-shell exit1 remain unchanged. Outside236 oldU3 elements remain unqualified. This protocol can establish only bounded finite fixed-patch integration agreement at the two frozen fields. It cannot establish analytic convergence, whole-body integration, equilibrium, physical deformation, tangent/displacement or anatomical-capstone completion. No field, physical law, gate, optimizer/refit or rule was changed; no publication or deployment occurred.','', '[Raw inventory](raw-inventory.json) · [Comparison table](comparisons.csv) · [Full summary](summary.json) · [Actual raw execution receipts](../fine-window-run-20261007/public-entry-exit.json)'];(OUT/'README.md').write_text('\n'.join(md)+'\n')
print(json.dumps({k:summary[k] for k in ['result','newCallbacks','requiredPass','requiredFail','informationalPass','informationalFail','combinedRawBytes','rawFileCount']}));print(json.dumps(comparisons))
