"""Independent read-only review of proposed future protocol; no law imports."""
import pathlib,json,math,hashlib
R=pathlib.Path('/workspace/Kenoma-patch-arithmetic-review');E=R/'education';OLD=E/'review/fixed-field-integration-run-20261007';SH=E/'review/element247-shell-run-20261007/material';NEW=E/'review/selective-fixed-patch-run-20261007/material';SEC=[197,200,203,206,246,248]
def rd(p):return json.loads(p.read_text())
source=next(x for x in rd(E/'data/anatomical-arm-v1/generated/arm-reference.json')['muscles'] if x['element_id']=='FJ1486');ids=source['elements_ten_node']
def tri(units):
 slots=[[[] for d in range(3)] for n in range(585)]
 for e,a,b in units:
  for i,n in enumerate(ids[e]):
   for d in range(3):slots[n][d].append(abs(a['localGradientsN']['total'][i][d]-b['localGradientsN']['total'][i][d]))
 return max(math.fsum(v) for row in slots for v in row)
values={}
for state in ['control45','terminal46']:
 ca=[rd(SH/f'{q}-{state}-assembly.json') for q in ['C55','A55']];af=[ca[1],rd(NEW/f'{state}-247-F44-stage.json')];values[f'{state}_247_C55_A55']=tri((247,a,b) for a,b in zip(ca[0]['comparisonShells'],ca[1]['comparisonShells']));values[f'{state}_247_A55_F44']=tri((247,a,b) for a,b in zip(af[0]['comparisonShells'],af[1]['comparisonShells']));values[f'{state}_secondary_D4_D5']=tri((e,rd(OLD/f'D4-{state}-element-{e}-local.json'),rd(OLD/f'D5-{state}-element-{e}-local.json')) for e in SEC);values[f'{state}_secondary_U5_D5']=tri((e,rd(OLD/f'U5-{state}-element-{e}-local.json'),rd(OLD/f'D5-{state}-element-{e}-local.json')) for e in SEC)
expected={'control45_247_C55_A55':1.2825659369687512e-8,'terminal46_247_C55_A55':8.611662232570753e-5,'control45_247_A55_F44':1.7481814376142503e-11,'terminal46_247_A55_F44':3.528012330541584e-7,'control45_secondary_D4_D5':6.419509190891404e-8,'terminal46_secondary_D4_D5':2.8679999530822897e-7,'terminal46_secondary_U5_D5':1.6174927040424336e-5}
for k,v in expected.items():assert abs(values[k]-v)<=1e-12,(k,values[k],v)
paths=['education/research/selective-fixed-patch-fine-window-criterion-20261007.md','education/review/selective-fixed-patch-arithmetic-review-20261007/README.md'];hashes={p:hashlib.sha256((R/p).read_bytes()).hexdigest() for p in paths};text=(R/paths[0]).read_text();ambiguous='Report decreasing differences on' in text
report={'verdict':'PASS_SCIENTIFIC_PROTOCOL_WORDING_WITH_MINOR_CLARIFICATION' if ambiguous else 'PASS_SCIENTIFIC_PROTOCOL_WORDING','reviewedSourceSha256':hashes,'frozenResultCommit':'38ae8a2e2af57cf33254af987b724824b9d84357','specimenCallsDuringReview':0,'materialLawInvocationsDuringReview':0,'newQuadratureGenerated':False,'frozenSourcesOrGatesEdited':False,'independentlyRecomputedHistoricalNumbers':values,'findings':['Diagnosis correctly distinguishes quadrature candidates from displacement states and Q2 mixed-family comparison from a universal refinement step.','Actual247angular1→2→4 sequence shares radial/depth/chart; declining finite increments are supported, without extending convergence or anatomical claims.','Historical secondary U5/D5 triangle failure remains visible and prevents treating D4/D5 same-grid order agreement as absolute error certification.','New prospectively frozen fine-window protocol legitimately archives immutable coarse-pair failure while demanding primary fine increments, resolved independent-family witness, finest cross-family comparison and separate axis checks.','Stable partitions, shared global force/work budgets, complete16support/all585held-node coverage and unchanged laws/gates/reconstruction limits are preserved.','Criterion supports bounded finite agreement only; outside236elements remain unqualified.'],'minorClarification': 'Replace Report decreasing differences on a matched partition with Report successive differences on a matched partition, including any decreases or increases, to avoid implying a monotonic acceptance gate that the following sentences explicitly reject.' if ambiguous else None,'remainingScientificBlockers':[]}
pathlib.Path('/tmp/selective-diagnosis-proposal-independent-review.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
