/** Oriented source-triangle measurements and connected surface selections. SI. */
export const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>a.map(v=>v/Math.hypot(...a));
export function surface(bone){
 const edges=new Map(),faces=bone.triangles.map((t,id)=>{const X=t.map(i=>bone.vertices_m[i]),n=cross(sub(X[1],X[0]),sub(X[2],X[0])),area=Math.hypot(...n)/2;return {id,centroid:X[0].map((_,d)=>X.reduce((s,x)=>s+x[d]/3,0)),normal:n.map(v=>v/(2*area)),area,vertices:X,neighbours:[]};});
 bone.triangles.forEach((t,id)=>t.forEach((v,i)=>{const key=[v,t[(i+1)%3]].sort((a,b)=>a-b).join(',');if(!edges.has(key))edges.set(key,[]);edges.get(key).push(id);}));for(const pair of edges.values())for(const i of pair)faces[i].neighbours.push(...pair.filter(j=>j!==i));return {bone,faces};
}
export function connectedRegion(s,predicate){
 const allowed=s.faces.map(predicate),seen=new Set(),components=[];for(const face of s.faces){if(!allowed[face.id]||seen.has(face.id))continue;const queue=[face.id];seen.add(face.id);for(let i=0;i<queue.length;i++)for(const j of s.faces[queue[i]].neighbours)if(allowed[j]&&!seen.has(j)){seen.add(j);queue.push(j);}components.push(queue);}
 if(!components.length)throw Error('No connected source patch');components.sort((a,b)=>b.reduce((s,i)=>s+sFaces(i).area,0)-a.reduce((s,i)=>s+sFaces(i).area,0));function sFaces(i){return s.faces[i];}return {ids:components[0],component_sizes:components.map(c=>c.length)};
}
export function geodesicRegion(s,seed,predicate,maxDistance){
 const distances=Array(s.faces.length).fill(Infinity),done=new Set();distances[seed]=0;const queue=[seed];while(queue.length){queue.sort((a,b)=>distances[b]-distances[a]);const i=queue.pop();if(done.has(i)||distances[i]>maxDistance)continue;done.add(i);for(const j of s.faces[i].neighbours){if(!predicate(s.faces[j]))continue;const d=distances[i]+Math.hypot(...sub(s.faces[i].centroid,s.faces[j].centroid));if(d<distances[j]&&d<=maxDistance){distances[j]=d;queue.push(j);}}}if(!done.size)throw Error('Empty geodesic source patch');return [...done].sort((a,b)=>a-b);
}
export function patchRecord(s,ids,label,selection){
 const area=ids.reduce((sum,i)=>sum+s.faces[i].area,0),weights=ids.map(i=>s.faces[i].area/area),centroid=[0,1,2].map(d=>ids.reduce((sum,i,k)=>sum+weights[k]*s.faces[i].centroid[d],0));
 return {element_id:s.bone.element_id,anatomical_label:label,triangle_indices_zero_based:ids,triangle_area_m2:ids.map(i=>s.faces[i].area),triangle_area_weights:weights,triangle_outward_normals_unit:ids.map(i=>s.faces[i].normal),triangle_centroids_m:ids.map(i=>s.faces[i].centroid),area_m2:area,area_weighted_centroid_m:centroid,selection,units:{positions:'m',area:'m2',normals:'unit vector',weights:'1'},evidence_class:'atlas_derived_authored_connected_surface_selection',review_status:'Independent anatomical review pending',limits:'Original source face ordering preserved after coordinate welding/orientation. Selection bounds and filtering are authored, not measured attachment extent.'};
}
export function solveDense(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let j=0;j<n;j++){let p=j;for(let i=j+1;i<n;i++)if(Math.abs(M[i][j])>Math.abs(M[p][j]))p=i;if(Math.abs(M[p][j])<1e-22)throw new RangeError('Singular diagnostic fit');[M[p],M[j]]=[M[j],M[p]];for(let i=j+1;i<n;i++){const factor=M[i][j]/M[j][j];for(let k=j;k<=n;k++)M[i][k]-=factor*M[j][k];}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--)x[i]=(M[i][n]-M[i].slice(i+1,n).reduce((s,v,k)=>s+v*x[i+1+k],0))/M[i][i];return x;}
export function smallestEigenvector3(matrix){const A=matrix.map(r=>r.slice()),V=[[1,0,0],[0,1,0],[0,0,1]];for(let iteration=0;iteration<60;iteration++){let p=0,q=1;for(const [i,j] of [[0,2],[1,2]])if(Math.abs(A[i][j])>Math.abs(A[p][q])){p=i;q=j;}if(Math.abs(A[p][q])<1e-16)break;const theta=.5*Math.atan2(2*A[p][q],A[q][q]-A[p][p]),c=Math.cos(theta),s=Math.sin(theta),rotation=[[1,0,0],[0,1,0],[0,0,1]];rotation[p][p]=c;rotation[q][q]=c;rotation[p][q]=s;rotation[q][p]=-s;const next=Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>[0,1,2].reduce((sum,k)=>sum+[0,1,2].reduce((s,l)=>s+rotation[k][i]*A[k][l]*rotation[l][j],0),0)));for(let i=0;i<3;i++){const row=V[i].slice();for(let j=0;j<3;j++)V[i][j]=[0,1,2].reduce((sum,k)=>sum+row[k]*rotation[k][j],0);}for(let i=0;i<3;i++)A[i]=next[i];}let i=0;for(let j=1;j<3;j++)if(A[j][j]<A[i][i])i=j;const eigenvector=unit(V.map(r=>r[i]));return {eigenvector:eigenvector[0]>0?eigenvector.map(v=>-v):eigenvector,eigenvalues:A.map((r,i)=>r[i]).sort((a,b)=>a-b)};}
