"""Lab 5's boundary/material extension, with a static print equivalent."""
def block(web):
    caption='Same Lab 5 homogeneous block and quadratic volume penalty. At imposed h = 0.8, free sides expand; confined sides cannot. Reactions and volume are outputs, not anatomical predictions.'
    if not web:return f'\n### Laboratory 5 extension · Bulk, shear and confinement\n\n![{caption}](assets/compression-reference.svg)\n\n{caption}\n\n[Open the compression experiment](index.html#lab-compression).\n'
    fields=''
    for param,label,low,high,step,value in [('mu','Shear modulus μ (Pa)',100,10000,100,1500),('bulk','Bulk modulus K (Pa)',0,1000000,1000,50000),('heightStretch','Imposed height stretch h',.6,1,.01,.8),('force','Imposed plate force (N)',0,20,.1,2)]:
        fields+=f'<div class="control"><label for="compression-{param}">{label}</label><div class="input-pair"><input type="range" aria-label="{label} slider" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"><input id="compression-{param}" type="number" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"></div></div>'
    for param,label,options in [('boundary','Lateral boundary',[('free','Free sides: zero lateral traction'),('confined','Confined sides: t = 1')]),('mode','Controlled quantity',[('displacement','Imposed height; measure reaction'),('force','Imposed force; solve height')])]:
        fields+=f'<div class="control"><label for="compression-{param}">{label}</label><select id="compression-{param}" data-param="{param}">'+''.join(f'<option value="{value}">{text}</option>' for value,text in options)+'</select></div>'
    return f'''\n<section class="laboratory property-lesson compression-lesson" data-compression="block" id="lab-compression" aria-labelledby="compression-heading"><h3 id="compression-heading">Laboratory 5 extension · Bulk, shear and confinement</h3><p class="model-label">Homogeneous quasistatic isotropic elasticity; frictionless plates; no spatial FEM or anatomical calibration.</p><figure class="static-figure"><img src="assets/compression-reference.svg" alt="{caption}"><figcaption>{caption}</figcaption></figure><div class="property-scene"></div><p>Height control accepts 0.6 ≤ h ≤ 1. Force inputs span 0–20 N and must also lie on the branch 0.8 ≤ h ≤ 1; its supported maximum is reported below. Unsupported loads retain the last valid state. Zero bulk with free sides has no unique force-controlled state.</p><div class="controls">{fields}</div><div class="actions"><button type="button" data-action="reset">Reset</button><button type="button" data-action="summary">Read current results</button><button type="button" data-action="copy">Copy state</button></div><dl class="readout" aria-label="Compression measurements and equilibrium checks"></dl><p class="announce" role="status" aria-live="polite"></p><textarea class="preset" aria-label="Reproducible compression JSON" readonly hidden></textarea><noscript>Interactive controls require JavaScript. The static comparison and derivation remain available.</noscript></section>\n'''
