"""Production and preview control specification for the axial SLS lesson."""
import html

def block(key='sls',web=True):
    if isinstance(key,bool):web=key;key='sls'
    if key not in ('sls','dissipative'):raise ValueError('Unknown dissipative lesson')
    title='Property lab 5 · Creep, relaxation and viscous loss'
    caption='Small-strain quasistatic axial standard linear solid: equilibrium spring in parallel with a Maxwell branch. Ramp, hold, unload and zero-force recovery expose history dependence. A force hold gives creep; a held extension gives force relaxation. Authored coefficients; no transverse equilibrium or muscle calibration.'
    if not web:return f'\n### {title}\n\n{caption}\n\n[Open the interactive protocol](index.html#lab-dissipative-bar).\n'
    fields=''
    for param,label,low,high,step,value in [('ratio','End area ratio A2/A1',.5,4,.1,2),('ramp','Loading and unloading ramp duration (s)',.1,2,.1,1),('hold','Hold duration (s)',.1,5,.1,2),('recovery','Zero-force recovery duration (s)',.1,5,.1,3),('force','Peak ramp force (N)',0,.6,.05,.6)]:
        fields+=f'<div class="control"><label for="dissipative-{param}">{label}</label><div class="input-pair"><input type="range" aria-label="{label} slider" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"><input id="dissipative-{param}" type="number" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"></div></div>'
    for param,label,options,default in [('eta','Viscosity η (Pa·s)',[(20000,'20,000'),(100000,'100,000'),(500000,'500,000')],100000),('E1','Maxwell spring E1 (Pa)',[(0,'Off: elastic limit'),(50000,'50,000'),(100000,'100,000'),(200000,'200,000')],100000),('holdMode','Hold condition',[('force','Fixed force: creep'),('extension','Held extension: relaxation')],'force'),('shape','Reference area profile',[('linear','Linear area taper'),('two-segment','Two equal-length segments')],'linear'),('segments','Midpoint cells',[(8,'8'),(16,'16'),(32,'32'),(64,'64'),(128,'128')],32),('dt','Physics observation step (s)',[(.01,'0.01'),(.02,'0.02'),(.05,'0.05')],.02)]:
        fields+=f'<div class="control"><label for="dissipative-{param}">{label}</label><select id="dissipative-{param}" data-param="{param}">'+''.join(f'<option value="{value}"'+(' selected' if value==default else '')+f'>{html.escape(label_text)}</option>' for value,label_text in options)+'</select></div>'
    return f'''\n<section class="laboratory property-lesson dissipative-lesson" data-dissipative="sls" id="lab-dissipative-bar" aria-labelledby="dissipative-heading"><h3 id="dissipative-heading">{title}</h3><p class="model-label">{caption}</p><p>Reference length 0.2 m; area A1 = 0.0003 m²; equilibrium modulus E0 = 100,000 Pa. E1 = 0 recovers the passive elastic bar.</p><p class="dissipative-policy"><strong>Each parameter edit starts a new experiment:</strong> time, internal strain, work, loss and trace reset; playback pauses. Invalid entries retain the prior experiment.</p><div class="dissipative-scene"></div><p class="dissipative-scale">Axial displacement is enlarged exactly ×10 at a fixed reference scale. Cell height shows reference area divided by a 0.01 m diagram depth; transverse deformation is not solved. Strain colors use one fixed palette: −0.05 <span class="dissipative-strain-key" aria-hidden="true"></span> +0.05. SI readouts are unscaled.</p><div class="controls">{fields}</div><div class="actions"><button type="button" data-action="reset">Reset defaults</button><button type="button" data-action="step">Single step</button><button type="button" data-action="play">Play</button><button type="button" data-action="run">Run protocol</button><button type="button" data-action="export">Download complete trace</button><button type="button" data-action="copy">Show trace JSON</button><button type="button" data-action="summary">Read current results</button></div><dl class="readout" aria-label="Current protocol and independent energy ledger"></dl><div class="dissipative-plots"><div class="dissipative-history"></div><div class="dissipative-energy"></div></div><p class="announce" role="status" aria-live="polite"></p><textarea class="preset" aria-label="Reproducible current experiment and complete protocol trace" readonly hidden></textarea><noscript>The protocol controls require JavaScript. Read the adjacent equations and numerical history table for the static lesson.</noscript></section>\n'''
