"""One control specification for production and the independently checked preview."""
import html

def block(web):
    title='Property lab 4 · Compression, bulk stiffness and confinement'
    caption='Solved homogeneous 80 × 60 × 50 mm reference block at height stretch 0.8, shear parameter 1,500 Pa and bulk parameter 50,000 Pa. Free: J = 0.993914, plate force 4.53637 N. Rigid unilateral walls: J = 0.8, plate force 42.0887 N. Dashed outlines are reference; gold lines are frictionless plates. Front view at one fixed physical scale; depth also scales by lateral stretch b.'
    if not web:return f'\n### {title}\n\n![{caption}](assets/property-material.svg)\n\n{caption}\n\n[Open the interactive lesson](index.html#lab-property-material).\n'
    fields=''
    for param,label,low,high,step,value in [('heightStretch','Prescribed height stretch h',.5,1,.01,.8),('mu','Shear parameter μ (Pa)',500,5000,100,1500),('bulk','Bulk parameter K (Pa)',0,250000,500,50000)]:
        fields+=f'<div class="control"><label for="material-{param}">{label}</label><div class="input-pair"><input type="range" aria-label="{label} slider" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"><input id="material-{param}" type="number" data-param="{param}" min="{low}" max="{high}" step="{step}" value="{value}"></div></div>'
    fields+='<div class="control"><label for="material-iterations">Bisection cap (per free root)</label><select id="material-iterations" data-param="iterations"><option value="8">8: finite approximation</option><option value="32">32</option><option value="64" selected>64</option></select></div>'
    return f'''\n<section class="laboratory property-lesson material-lesson" data-material="compression" id="lab-property-material" aria-labelledby="material-heading"><h3 id="material-heading">{title}</h3><p class="model-label">Homogeneous quasistatic elastic equilibrium; shared prescribed height; free sides versus unilateral rigid walls. Authored parameters, SI units; no muscle calibration.</p><figure class="static-figure"><img src="assets/property-material.svg" alt="{html.escape(caption)}"><figcaption>{caption}</figcaption></figure><div class="property-scene"></div><p class="property-description">Front view of the solved blocks at the same height and fixed physical scale. Dashed: reference. Gold: frictionless plates. Red walls: compressive contact; gray walls allow pull-away. Both unshown depths also scale by b. Numerical values are unscaled SI. Finite residual success does not establish physical validity.</p><div class="controls">{fields}</div><div class="actions"><button type="button" data-action="reset">Reset</button><button type="button" data-action="candidate">Test isochoric wall candidate</button><button type="button" data-action="summary">Read current results</button><button type="button" data-action="copy">Copy state</button></div><dl class="readout" aria-label="Free and confined equilibrium measurements"></dl><p class="announce" role="status" aria-live="polite"></p><textarea class="preset" aria-label="Reproducible compression JSON" readonly hidden></textarea><noscript>Interactive controls require JavaScript. The solved default figure, derivation and table remain available.</noscript></section>\n'''
