import * as THREE from 'three';
import {seriesResults} from './series.mjs';
import {SPATIAL,SPATIAL_MESH as mesh,spatialInitial,spatialStep,spatialResults,rotate} from './spatial.mjs';
import {makeCase,solveReference,solveCompliant,diagnose,difference,continuumError} from '../contributions/continuum_reference/continuum.mjs';
const fd=(x,d=3)=>Math.abs(x)<1e-12?'0':Math.abs(x)>1e5?x.toExponential(3):x.toFixed(d);
const CONTINUUM={n:3,case:'quadratic',h:.0005,sweeps:5,comparison:'implicit',magnification:50};
export class AdvancedView{
 constructor(root,activate){
  this.root=root;this.kind=root.dataset.advanced;this.activate=activate;this.host=root.querySelector('.scene-host');this.status=root.querySelector('.announce');this.view='front';this.running=false;
  root.querySelectorAll('[data-param]').forEach(input=>input.addEventListener('input',()=>this.change(input)));
  for(const [action,fn] of Object.entries({start:()=>this.start(),reset:()=>this.reset(),view:()=>{this.view=this.view==='front'?'oblique':'front';this.draw();this.status.textContent=`${this.view} view; numerical state unchanged.`;},step:()=>{this.pause();this.step();},play:()=>this.running?this.pause():this.play(),release:()=>{this.pulse=false;this.params.excitation=0;this.sync();this.update(false);this.status.textContent='Released excitation; activation, pose and spatial state are unchanged until the next step.';},pulse:()=>{this.reset();this.pulse=true;this.play();},compression:()=>{this.pause();this.params.mode='prescribed';this.params.angle=90;this.params.sweeps=640;this.state=spatialInitial(this.params);this.state.a=.6;this.index=0;this.history=[];this.sync();this.update();this.status.textContent='Same-pose compression fixture: q = 90°, a = 0.6, finite quasistatic solve, 640-iteration cap. No time advanced.';},summary:()=>{this.status.textContent=root.querySelector('.readout').textContent;},copy:()=>this.copy(),export:()=>this.export()}))root.querySelector(`[data-action=${action}]`)?.addEventListener('click',fn);
  this.reset();
 }
 sync(){this.root.querySelectorAll('[data-param]').forEach(el=>{el.value=this.params[el.dataset.param];el.removeAttribute('aria-invalid');});}
 change(input){
  const key=input.dataset.param,isString=['case','comparison','mode','tendon','boneContact','skin','activeShape'].includes(key),v=isString?input.value:Number(input.value);
  if(!isString&&(input.value===''||!Number.isFinite(v)||(input.min!==''&&v<Number(input.min))||(input.max!==''&&v>Number(input.max)))){input.setAttribute('aria-invalid','true');this.status.textContent='Enter a finite value within the displayed limits.';return;}
  input.removeAttribute('aria-invalid');this.params[key]=v;this.root.querySelectorAll(`[data-param="${key}"]`).forEach(el=>{if(el!==input)el.value=v;});this.status.textContent='Input applied within the documented model limits.';
  if(this.kind==='spatial'&&key==='excitation'){this.pulse=false;this.update(false);return;}
  this.pause();if(this.kind==='spatial'){this.state=spatialInitial(this.params);this.index=0;this.history=[];this.pulse=false;}
  if(this.kind==='continuum'&&['n','case'].includes(key))this.problem=null;
  this.update();
 }
 reset(){this.pause();this.params={...(this.kind==='spatial'?SPATIAL:CONTINUUM)};this.state=this.kind==='spatial'?spatialInitial(this.params):null;this.problem=null;this.assemblyCount=0;this.index=0;this.history=[];this.pulse=false;this.view='front';this.sync();this.update();this.status.textContent='Reset to the documented deterministic state; playback paused.';}
 pause(){this.running=false;cancelAnimationFrame(this.frame);const b=this.root.querySelector('[data-action=play]');if(b)b.textContent='Play';}
 play(){if(this.state?.halted||this.index>=240)return;this.activate(this);this.running=true;this.root.querySelector('[data-action=play]').textContent='Pause';let last=0;const tick=t=>{if(!this.running)return;if(t-last>=100){this.step();last=t;}if(this.running)this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);}
 step(){if(this.kind!=='spatial'||this.state.halted||this.index>=240){this.pause();return;}if(this.pulse&&this.state.time>=.3&&this.params.excitation!==0){this.params.excitation=0;this.sync();this.update(false);}this.state=spatialStep(this.state,this.params);if(this.state.halted){this.pause();this.status.textContent='Paused at the last pose within the 0–100° teaching domain; joint impact is absent.';}else this.index++;this.update();if(this.index>=240)this.pause();}
 copy(){const text=JSON.stringify({schema:1,model:this.kind,parameters:this.params,state:this.state,step:this.index,view:this.view,diagnostics:this.scalar},null,2),p=this.root.querySelector('.preset');p.hidden=false;p.value=text;p.focus();p.select();this.status.textContent='Reproducible parameters, state and unscaled diagnostics shown below.';}
 export(){const payload={schema:1,model:'one-way-spatial-arm-v1',units:'SI; q radians',parameters:this.params,tracePolicy:'Current row refreshed after excitation changes, without advancing state or spatial solve. Spatial energies are instantaneous quasistatic energies, not hinge work.',trace:this.history};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='kenoma-spatial-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);this.status.textContent='Downloaded the one-way spatial trace with its approximation labels.';}
 update(solve=true){
  this.root.querySelector('.preset').hidden=true;let rows;
  if(this.kind==='spatial'){
   if(solve||!this.result)this.result=spatialResults(this.state,this.params);else this.result.hinge=seriesResults(this.state,{...this.params,contact:'off'});
   const {shape:r,hinge:h}=this.result,s=this.state;
   this.scalar={time:s.time,q:s.q,activation:s.a,excitation:this.params.excitation,hingeWorkJ:s.work,hingeFiberM:h.fiber,hingeFiberSpeedMPerS:h.fiberSpeed,hingeActivePowerW:h.activePower,spatialMuscleM:r.muscleLengthM,spatialFiberArcM:r.fiberArcLengthM,spatialMeanFiberArcM:r.meanFiberArcM,spatialTendonM:r.tendonLengthM,minJ:r.minJ,meanJ:r.meanJ,baselineMinJ:r.baselineMinJ,baselineMeanJ:r.baselineMeanJ,contactNormalSumN:r.contactNormalSumN,penetrationM:r.maxPenetrationM,baselinePenetrationM:r.baselinePenetrationM,maxFreeForceN:r.maxFreeForceN,freeResidualN:r.freeResidualN,forceBalanceN:r.forceBalanceN,energyJ:r.energy,iterations:r.iterations,converged:r.converged};
   const row={step:this.index,...this.scalar},i=this.history.findIndex(v=>v.step===this.index);if(i>=0)this.history[i]=row;else this.history.push(row);
   rows=[['Coupling','One-way: hinge → quasistatic tissue'],['Time',`${fd(s.time)} s`],['Same flexion q',`${fd(s.q*180/Math.PI,2)}°`],['Excitation u / activation a',`${fd(this.params.excitation)} / ${fd(s.a)}`],['Line actuator tension',`${fd(h.tension,2)} N`],['Hinge angular velocity',`${fd(s.w)} rad/s`],['Line / gravity moments',`${fd(h.muscleTorque)} / ${fd(h.gravityTorque)} N m`],['External prescribed hold moment',`${fd(h.motorTorque)} N m`],['Active line fibre power / work',`${fd(h.activePower)} W / ${fd(s.work)} J`],['Line fibre length / speed',`${fd(h.fiber,4)} m / ${fd(h.fiberSpeed,4)} m/s`],['Spatial fibre path centre / mean',`${fd(r.fiberArcLengthM,5)} / ${fd(r.meanFiberArcM,5)} m`],['Spatial end-to-end active span',`${fd(r.muscleLengthM,5)} m`],['Spatial tendon-span length',`${fd(r.tendonLengthM,5)} m`],['Volume J min / mean',`${fd(r.minJ,4)} / ${fd(r.meanJ,4)}`],['Same-pose LBS J min / mean',`${fd(r.baselineMinJ,4)} / ${fd(r.baselineMeanJ,4)}`],['Sampled normal-force sum',`${fd(r.contactNormalSumN,3)} N`],['Sampled penetration / LBS',`${fd(r.maxPenetrationM*1000,4)} / ${fd(r.baselinePenetrationM*1000,4)} mm`],['Free-force residual L2 / max',`${fd(r.freeResidualN,4)} / ${fd(r.maxFreeForceN,4)} N`],['Force-balance defect norm',`${fd(Math.hypot(...r.forceBalanceN),4)} N`],['Elastic/contact energy',`${fd(r.total,5)} J`],['Skin / fascia energy',`${fd(r.energy.skin,5)} / ${fd(r.energy.fascia,5)} J`],['Iterations / energy evaluations',`${r.iterations} / ${r.evaluations}`],['Solve status',r.converged?'Local residual criterion reached':'Finite-iteration approximation'],['Contact interpretation','Compliant vertex/centroid samples; pressure absent']];
  }else{
   const p=this.params;if(!this.problem){this.problem=makeCase({n:p.n,kind:p.case});this.referenceCache=new Map();this.assemblyCount=(this.assemblyCount||0)+1;}
   const problem=this.problem,key=p.comparison==='static'?'static':String(p.h);let reference=this.referenceCache.get(key);
   if(!reference){reference=solveReference(problem,p.comparison==='static'?{}:{h:p.h});if(!reference.converged)throw new Error('FEM reference did not converge');this.referenceCache.set(key,reference);}
   const isStatic=p.comparison==='static',fast=isStatic?{u:Float64Array.from(problem.mesh.nodes.flatMap(X=>problem.exact(X)))}:solveCompliant(problem,{h:p.h,sweeps:p.sweeps});
   const referenceDiag=diagnose(problem,reference.u,isStatic?{}:{h:p.h}),metrics=isStatic?continuumError(problem,reference.u):difference(problem,fast.u,reference.u,{h:p.h}),fastDiag=isStatic?null:diagnose(problem,fast.u,{h:p.h});this.result={reference,fast,referenceDiag,fastDiag,metrics,isStatic};
   this.scalar={comparison:p.comparison,parameters:p,assemblyCount:this.assemblyCount,referenceConverged:reference.converged,referenceResidualN:referenceDiag.residualN,metrics,fastResidualN:fastDiag?.residualN};
   rows=[['Target',isStatic?'Static manufactured continuum solution':'One backward-Euler step from rest'],['Nodes / tetrahedra',`${problem.mesh.nodes.length} / ${problem.mesh.tets.length}`],['E / ν','100,000 Pa / 0.25 (authored)'],['Common display magnification',`${p.magnification}× displacement only`],['Reference status','Freshly checked discrete residual criterion'],['Reference free residual',`${referenceDiag.residualN.toExponential(3)} N`],['Largest applied nodal load',`${fd(Math.max(...problem.mesh.nodes.map((_,i)=>Math.hypot(...problem.force.slice(3*i,3*i+3)))),5)} N`],['PCG iterations',String(reference.iterations)],['Reference elastic energy',`${referenceDiag.energyJ.toExponential(4)} J`],...(isStatic?[['Static analytic displacement L2 error',`${fd(100*metrics.relativeL2,3)} %`],['Static analytic energy-norm error',`${fd(100*metrics.relativeEnergy,3)} %`]]:[['Common h',`${p.h} s`],['Compliant sweeps',String(p.sweeps)],['Matched implicit objective-norm error',`${fd(100*metrics.relativeObjectiveNorm,3)} %`],['Max nodal difference',`${fd(metrics.maxNodalM*1000,6)} mm`],['Compliant free residual',`${fastDiag.residualN.toExponential(4)} N`],['Compliant force-balance defect',`${Math.hypot(...fastDiag.balanceN).toExponential(4)} N`]]),['Material limit','Small strain; nonobjective at finite rotation; no contact']];
  }
  this.root.querySelector('.readout').replaceChildren(...rows.map(([label,value])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);return div;}));this.draw();
 }
 start(){this.activate(this);if(!this.renderer)try{this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setClearColor(0x101d2c);this.renderer.domElement.setAttribute('role','img');this.renderer.domElement.setAttribute('aria-label',`${this.kind} paired 3D comparison; numerical results and text alternative follow.`);this.host.replaceChildren(this.renderer.domElement);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(36,1,.01,100);this.observer=new ResizeObserver(()=>this.draw());this.observer.observe(this.host);}catch{this.stopRenderer();this.status.textContent='3D unavailable; numerical controls, static figure and text remain usable.';return;}this.root.classList.add('active-scene');this.draw();}
 stopRenderer(){this.pause();this.observer?.disconnect();this.scene?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.renderer?.dispose();this.renderer?.forceContextLoss();this.renderer=null;this.host.replaceChildren();this.root.classList.remove('active-scene');}
 draw(){
  if(!this.renderer)return;this.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.scene.clear();this.scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(1,2,4);this.scene.add(light);
  const surf=(x,faces,color,offset,scale,wire=false,alpha=1)=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(x.map(X=>[offset+scale*X[0],scale*(X[1]-.04),scale*X[2]]).flat(),3));g.setIndex(faces.flat());g.computeVertexNormals();const obj=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,side:THREE.DoubleSide,roughness:.7,transparent:alpha<1,opacity:alpha,wireframe:wire,depthWrite:alpha===1}));this.scene.add(obj);};
  const rod=(A,B,r,color,offset,scale)=>{const a=new THREE.Vector3(offset+scale*A[0],scale*(A[1]-.04),scale*A[2]),b=new THREE.Vector3(offset+scale*B[0],scale*(B[1]-.04),scale*B[2]),d=b.clone().sub(a);const obj=new THREE.Mesh(new THREE.CylinderGeometry(r*scale,r*scale,d.length(),18),new THREE.MeshStandardMaterial({color}));obj.position.copy(a.add(b).multiplyScalar(.5));obj.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());this.scene.add(obj);};
  if(this.kind==='spatial'){
   const r=this.result.shape,q=this.state.q,scale=4.5;
   for(const [side,offset] of [[0,-1.1],[1,.65]]){
    const x=side===0?r.x:r.baseline;
    rod([0,0,0],[0,.27,0],.021,0xe8cf9b,offset,scale);rod([0,0,0],rotate([0,-this.params.length,0],q),.019,0xe8cf9b,offset,scale);for(const [X,radius] of [[[0,0,0],.021],[[0,.27,0],.021],[rotate([0,-this.params.length,0],q),.019]]){const bone=new THREE.Mesh(new THREE.SphereGeometry(radius*scale,18,12),new THREE.MeshStandardMaterial({color:0xe8cf9b}));bone.position.set(offset+scale*X[0],scale*(X[1]-.04),scale*X[2]);this.scene.add(bone);}
    const end=rotate([0,-this.params.length,0],q);if(this.params.load>0)this.scene.add(new THREE.ArrowHelper(new THREE.Vector3(0,-1,0),new THREE.Vector3(offset+scale*end[0],scale*(end[1]-.04)-.13,0),.1+.035*this.params.load,0xffc66d,.06,.035));rod([end[0]-.045,end[1],0],[end[0]+.045,end[1],0],.022,0x8393a1,offset,scale);
    surf(x,mesh.surface,side===0?0xff856f:0x9bafff,offset,scale,false,.88);
    if(this.params.skin==='on'||side===1){surf(x,mesh.skinSurface,side===0?0x70e0cc:0xb6c5ff,offset,scale,false,.2);surf(x,mesh.skinSurface,side===0?0x70e0cc:0xb6c5ff,offset,scale,true,.65);}
    for(let j=0;j<4;j++)rod(x[j*9+4],x[(j+1)*9+4],.0015,0xe8483f,offset,scale);
    rod(x[4*9+4],x[5*9+4],.002,0xffc66d,offset,scale);
   }
   for(const c of r.contacts.filter(c=>c.N>.05).slice(0,20)){const g=new THREE.SphereGeometry(.012,10,8),o=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0xffff00}));o.position.set(-1.1+scale*c.point[0],scale*(c.point[1]-.04),scale*c.point[2]);this.scene.add(o);}
  }else{
   const p=this.problem,r=this.result,scale=22;
   for(const [u,offset,color] of [[r.reference.u,-1.4,0x70e0cc],[r.fast.u,.4,0x9bafff]]){
    const x=p.mesh.nodes.map((X,i)=>X.map((v,d)=>v+this.params.magnification*u[3*i+d]));surf(x,p.mesh.surface.map(f=>f.tri),color,offset,scale);surf(p.mesh.nodes,p.mesh.surface.map(f=>f.tri),0x8393a1,offset,scale,true,.5);
    rod([0,0,0],[0,p.mesh.lengths[1],0],.001,0xffc66d,offset,scale);const loadNodes=p.mesh.nodes.map((_,i)=>({i,F:Array.from(p.force.slice(3*i,3*i+3))})).sort((a,b)=>Math.hypot(...b.F)-Math.hypot(...a.F)),maxF=Math.hypot(...loadNodes[0].F);for(const {i,F} of loadNodes.slice(0,6)){const f=new THREE.Vector3(...F),X=x[i];if(f.length()>1e-12)this.scene.add(new THREE.ArrowHelper(f.clone().normalize(),new THREE.Vector3(offset+scale*X[0],scale*(X[1]-.04),scale*X[2]),.16*f.length()/maxF,0xff876f,.035,.02));}
   }
  }
  const width=Math.max(200,this.host.clientWidth);this.renderer.setSize(width,420,false);this.camera.aspect=width/420;const bounds=new THREE.Box3().setFromObject(this.scene),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),tan=Math.tan(this.camera.fov*Math.PI/360),distance=1.25*Math.max(size.y/(2*tan),size.x/(2*tan*this.camera.aspect))+.15;this.camera.position.copy(center).add(new THREE.Vector3(this.view==='front'?0:.35*distance,this.view==='front'?0:.2*distance,distance));this.camera.lookAt(center);this.camera.updateProjectionMatrix();this.renderer.render(this.scene,this.camera);
 }
}
