import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {TransformControls} from './vendor/TransformControls.js';
const names={rightArm:'Right arm',leftArm:'Left arm',rightLeg:'Right leg',leftLeg:'Left leg'};
const v=a=>new THREE.Vector3(...a);
export class SceneRenderer {
 constructor(container,client,model,onChange,onError){
  Object.assign(this,{container,client,model,onChange,onError});this.characters=new Map();this.handles=new Map();this.selectedHandle='root';this.syncing=false;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#101b24');this.scene.fog=new THREE.Fog('#101b24',12,35);
  this.camera=new THREE.PerspectiveCamera(42,1,.01,100);this.camera.position.set(2.8,2.1,4.8);
  this.webgl=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.webgl.setPixelRatio(Math.min(devicePixelRatio,2));this.webgl.outputColorSpace=THREE.SRGBColorSpace;container.append(this.webgl.domElement);
  this.controls=new OrbitControls(this.camera,this.webgl.domElement);this.controls.target.set(0,.95,0);this.controls.enableDamping=true;this.controls.minDistance=.6;this.controls.maxDistance=30;
  this.scene.add(new THREE.HemisphereLight(0xdcecff,0x445346,2.4));const light=new THREE.DirectionalLight(0xffffff,2.2);light.position.set(3,6,5);this.scene.add(light);
  this.floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x182832,roughness:1}));this.floor.rotation.x=-Math.PI/2;this.floor.position.y=-.012;this.scene.add(this.floor);
  this.grid=new THREE.GridHelper(30,60,0x648579,0x38515b);this.grid.position.y=-.008;this.scene.add(this.grid);
  this.handleGroup=new THREE.Group();this.scene.add(this.handleGroup);
  this.gizmo=new TransformControls(this.camera,this.webgl.domElement);this.gizmo.setSize(.7);this.scene.add(this.gizmo.getHelper());
  this.gizmo.addEventListener('dragging-changed',e=>{if(this.cancelling)return;this.controls.enabled=!e.value;if(e.value){this.activePointerId=this.lastPointerDownId;this.model.beginGesture();}else{this.activePointerId=null;this.model.commitGesture();this.onChange();}});
  this.gizmo.addEventListener('objectChange',()=>{if(!this.syncing&&this.gizmo.object)this.applyHandle(this.gizmo.object);});
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.drag=null;
  const canvas=this.webgl.domElement;
  canvas.addEventListener('pointerdown',e=>this.pointerDown(e),true);canvas.addEventListener('pointermove',e=>this.pointerMove(e),true);canvas.addEventListener('pointerup',e=>this.pointerUp(e),true);canvas.addEventListener('pointercancel',e=>{if(!this.allowPointer(e))return;if(this.drag||this.gizmo.dragging){e.stopImmediatePropagation();this.cancelDrag();}},true);
  canvas.setAttribute('aria-label','3D character scene: drag rig handles to pose');canvas.tabIndex=0;
  new ResizeObserver(()=>this.resize()).observe(container);this.resize();this.sync();this.webgl.setAnimationLoop(()=>{this.controls.update();this.webgl.render(this.scene,this.camera);});
 }
 resize(){const {width,height}=this.container.getBoundingClientRect();this.camera.aspect=width/Math.max(height,1);this.camera.updateProjectionMatrix();this.webgl.setSize(width,height);if(this.characters.size)this.frame();}
 meshGeometry(mesh){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(mesh.positions.flat(),3));geometry.setAttribute('normal',new THREE.Float32BufferAttribute(mesh.normals.flat(),3));const indices=[];for(let i=0;i<mesh.indices.length;i+=3){const ids=mesh.indices.slice(i,i+3);if(ids.some(id=>mesh.source_edges[id]===2||mesh.source_nodes[id]===3))continue;indices.push(...ids);}geometry.setIndex(indices);geometry.computeBoundingSphere();return geometry;}
 makeCharacter(c){const group=new THREE.Group();group.userData.characterId=c.id;const material=new THREE.MeshStandardMaterial({color:c.color,roughness:.68});const body=new THREE.Mesh(new THREE.BufferGeometry(),material);group.add(body);
  const head=new THREE.Group();const skull=new THREE.Mesh(new THREE.SphereGeometry(1,24,18),material);skull.scale.set(.12,.16,.125);head.add(skull);
  const face=new THREE.Mesh(new THREE.BoxGeometry(.14,.12,.04),material);face.position.set(0,-.025,.105);head.add(face);
  const nose=new THREE.Mesh(new THREE.ConeGeometry(.025,.072,4),material);nose.rotation.x=Math.PI/2;nose.position.set(0,0,.16);head.add(nose);
  const eyeMat=new THREE.MeshStandardMaterial({color:0x17232c});for(const x of [-.047,.047]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.011,12,8),eyeMat);eye.position.set(x,.04,.119);head.add(eye);}
  const back=new THREE.Mesh(new THREE.SphereGeometry(1,20,12),new THREE.MeshStandardMaterial({color:0x283640,roughness:1}));back.scale.set(.121,.12,.075);back.position.set(0,.036,-.06);head.add(back);group.add(head);
  this.scene.add(group);return {group,body,head,material,graphKey:null};
 }
 sync(){this.syncing=true;try{const state=this.model.state;for(const [id,item]of this.characters){if(!state.characters.some(c=>c.id===id)){this.scene.remove(item.group);item.group.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});this.characters.delete(id);}}
  for(const c of state.characters){let item=this.characters.get(c.id);if(!item){item=this.makeCharacter(c);this.characters.set(c.id,item);}item.group.position.fromArray(c.position);item.group.rotation.y=c.yaw;item.material.color.set(c.color);const key=JSON.stringify(c.graph);if(item.graphKey!==key){const r=this.client.request({version:1,operation:{type:'generate',graph:JSON.parse(key)}});if(!r.ok)throw Error(r.error.message);item.body.geometry.dispose();item.body.geometry=this.meshGeometry(r.mesh);item.graphKey=key;item.mesh=r.mesh;}item.head.position.fromArray(c.graph.nodes[3].position);item.head.rotation.set(c.head.pitch,c.head.yaw,0,'YXZ');}
  const c=state.characters.find(c=>c.id===state.selectedId);if(!c){this.gizmo.detach();this.handleGroup.visible=false;return;}this.handleGroup.visible=true;const item=this.characters.get(c.id);item.group.updateMatrixWorld(true);
  const data=[['root',c.graph.nodes[0].position],...Object.entries(c.rig).flatMap(([limb,r])=>[[limb+':target',r.target],[limb+':pole',r.pole]])];
  for(const [key,pos]of data){let handle=this.handles.get(key);if(!handle){const pole=key.endsWith(':pole');handle=new THREE.Mesh(pole?new THREE.OctahedronGeometry(.038):new THREE.SphereGeometry(key==='root'?.063:.047,16,12),new THREE.MeshBasicMaterial({color:pole?0xf5bb70:0x80f7dc,depthTest:false,transparent:true,opacity:.92}));handle.renderOrder=10;handle.userData.handle=key;this.handles.set(key,handle);this.handleGroup.add(handle);}handle.position.copy(item.group.localToWorld(v(pos)));handle.material.color.set(key===this.selectedHandle?0xffffff:key.endsWith(':pole')?0xf5bb70:0x80f7dc);}
  this.gizmo.attach(this.handles.get(this.selectedHandle));
 }finally{this.syncing=false;}}
 selectHandle(key){if(!this.handles.has(key))return;this.selectedHandle=key;this.sync();this.onChange();}
 applyHandle(handle){const c=this.model.state.characters.find(c=>c.id===this.model.state.selectedId);if(!c)return;try{if(handle.userData.handle==='root'){const item=this.characters.get(c.id);const root=item.group.localToWorld(v(c.graph.nodes[0].position));const delta=handle.position.clone().sub(root);this.model.dispatch({type:'placement',id:c.id,position:v(c.position).add(delta).toArray()});}else{const [limb,kind]=handle.userData.handle.split(':');const item=this.characters.get(c.id);item.group.updateMatrixWorld(true);this.model.dispatch({type:'ik',id:c.id,limb,[kind]:item.group.worldToLocal(handle.position.clone()).toArray()});}this.onChange();}catch(e){this.onError(e);this.sync();}}
 ray(e){const r=this.webgl.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);}
 allowPointer(e){if(this.activePointerId!=null&&e.pointerId!==this.activePointerId){e.stopImmediatePropagation();e.preventDefault();return false;}return true;}
 pointerDown(e){if(!this.allowPointer(e))return;if(this.drag||this.gizmo.dragging){e.stopImmediatePropagation();e.preventDefault();return;}this.lastPointerDownId=e.pointerId;this.webgl.domElement.focus({preventScroll:true});if(e.button!==0)return;this.ray(e);const hit=this.handleGroup.visible?this.raycaster.intersectObjects([...this.handles.values()])[0]:null;if(hit){e.stopImmediatePropagation();e.preventDefault();this.selectHandle(hit.object.userData.handle);const plane=new THREE.Plane().setFromNormalAndCoplanarPoint(this.camera.getWorldDirection(new THREE.Vector3()),hit.object.position);const point=new THREE.Vector3();this.raycaster.ray.intersectPlane(plane,point);this.drag={object:hit.object,plane,offset:hit.object.position.clone().sub(point),pointerId:e.pointerId};this.activePointerId=e.pointerId;this.model.beginGesture();this.controls.enabled=false;this.webgl.domElement.setPointerCapture(e.pointerId);return;}
  // Gizmo axes get priority over body selection; OrbitControls owns empty space.
  if(this.gizmo.axis)return;const bodyHits=this.raycaster.intersectObjects([...this.characters.values()].map(i=>i.group),true);if(bodyHits.length){let o=bodyHits[0].object;while(o&&!o.userData.characterId)o=o.parent;if(o){this.model.dispatch({type:'select',id:o.userData.characterId});this.onChange();}}
 }
 pointerMove(e){if(!this.allowPointer(e))return;if(!this.drag)return;e.stopImmediatePropagation();e.preventDefault();if(e.pointerId!==this.drag.pointerId)return;this.ray(e);const point=new THREE.Vector3();if(this.raycaster.ray.intersectPlane(this.drag.plane,point)){this.drag.object.position.copy(point.add(this.drag.offset));this.applyHandle(this.drag.object);}}
 pointerUp(e){if(!this.allowPointer(e))return;this.activePointerId=null;if(!this.drag)return;e.stopImmediatePropagation();if(e.pointerId!==this.drag.pointerId)return;if(this.webgl.domElement.hasPointerCapture(e.pointerId))this.webgl.domElement.releasePointerCapture(e.pointerId);this.drag=null;this.controls.enabled=true;this.model.commitGesture();this.onChange();}
 cancelDrag(){if(!this.drag&&!this.gizmo.dragging)return;this.cancelling=true;this.syncing=true;try{const pointerId=this.activePointerId;if(pointerId!==undefined&&this.webgl.domElement.hasPointerCapture(pointerId))this.webgl.domElement.releasePointerCapture(pointerId);this.drag=null;this.activePointerId=null;this.gizmo.reset();this.gizmo.dragging=false;this.model.cancelGesture();this.controls.enabled=true;}finally{this.cancelling=false;this.syncing=false;}this.onChange();}
 frame(){const box=new THREE.Box3();for(const c of this.characters.values())box.expandByObject(c.group);if(this.handleGroup.visible&&this.handles.size)box.expandByObject(this.handleGroup);if(box.isEmpty())box.setFromCenterAndSize(new THREE.Vector3(0,.9,0),new THREE.Vector3(2,2,2));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const distance=Math.max(size.y,size.x/this.camera.aspect,1)/Math.tan(this.camera.fov*Math.PI/360)*.7;this.controls.target.copy(center);this.camera.position.copy(center).add(new THREE.Vector3(.45,.22,1).normalize().multiplyScalar(distance));this.controls.update();}
 projectHandle(key){const h=this.handles.get(key);if(!h)return null;this.camera.updateMatrixWorld();const p=h.position.clone().project(this.camera),r=this.webgl.domElement.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}
 getHandleScreenPosition(limb,kind){return this.projectHandle(kind?`${limb}:${kind}`:limb);}
}
