import test from 'node:test';
import assert from 'node:assert/strict';
import {AsyncRigBridge} from '../rig-bridge.js';
function fixture(){const sent=[],handlers={},meshes=[],errors=[];const worker={addEventListener:(type,fn)=>handlers[type]=fn,postMessage:job=>sent.push(structuredClone(job)),terminate(){this.terminated=true;}};const bridge=new AsyncRigBridge({workerFactory:()=>worker,onMesh:mesh=>meshes.push(mesh),onError:error=>errors.push(error.message)});return {bridge,worker,sent,meshes,errors,reply:(job=sent.at(-1),extra={})=>handlers.message({data:{jobId:job.jobId,ok:true,mesh:{marker:job.revision},...extra}}),crash:()=>handlers.error({message:'worker crash'})};}
const graph=x=>({nodes:[{position:[x,0,0]}],edges:[]}),head={yaw:0,pitch:0};
test('bind precedes pose and latest pending poses coalesce without blocking caller',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);f.reply();assert.equal(f.sent.at(-1).type,'pose');const old=f.sent.at(-1);for(let i=2;i<=100;i++)f.bridge.pose('a',graph(i),head);assert.equal(f.sent.length,2);assert.equal(f.bridge.queue.length,1);f.reply(old);assert.equal(f.meshes.length,0);assert.equal(f.sent.at(-1).graph.nodes[0].position[0],100);f.reply();await f.bridge.whenIdle();assert.equal(f.meshes.length,1);assert.equal(f.meshes[0].revision,100);assert.equal(f.bridge.pending,false);});
test('queued and inflight poses cannot mutate when caller graph changes',async()=>{const f=fixture(),g=graph(1);f.bridge.bind('a',graph(0));f.bridge.pose('a',g,head);g.nodes[0].position[0]=99;f.reply();assert.equal(f.sent.at(-1).graph.nodes[0].position[0],1);f.reply();await f.bridge.whenIdle();});
test('undo to an older pose rejects the now stale inflight geometry',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(0),head);f.reply();f.reply();f.bridge.pose('a',graph(2),head);const changing=f.sent.at(-1);f.bridge.pose('a',graph(0),head);f.reply(changing);assert.equal(f.meshes.length,1);assert.equal(f.sent.at(-1).graph.nodes[0].position[0],0);f.reply();await f.bridge.whenIdle();assert.equal(f.meshes.length,2);assert.equal(f.meshes.at(-1).revision,3);});
test('remove and re-add same id uses a new incarnation and discards old output',async()=>{const f=fixture();const generation=f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);f.reply();const old=f.sent.at(-1);f.bridge.remove('a');const next=f.bridge.bind('a',graph(0));assert.notEqual(next,generation);f.bridge.pose('a',graph(7),head);f.reply(old);assert.equal(f.meshes.length,0);assert.equal(f.sent.at(-1).type,'release');f.reply();assert.equal(f.sent.at(-1).type,'bind');f.reply();f.reply();await f.bridge.whenIdle();assert.equal(f.meshes.length,1);assert.equal(f.meshes[0].generation,next);});
test('multiple characters have independent queues and stale revisions',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);f.bridge.bind('b',graph(0));f.bridge.pose('b',graph(2),head);f.reply();f.bridge.pose('a',graph(3),head);f.reply();assert.equal(f.meshes.length,0);f.reply();f.reply();f.reply();await f.bridge.whenIdle();assert.deepEqual(f.meshes.map(m=>m.id),['b','a']);assert.equal(f.meshes[0].revision,1);assert.equal(f.meshes[1].revision,2);});
test('binding errors reject idle waits and skip impossible pose jobs',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);const idle=f.bridge.whenIdle();f.reply(undefined,{ok:false,error:{message:'bad binding'}});await assert.rejects(idle,/bad binding/);assert.equal(f.bridge.pending,false);assert.deepEqual(f.errors,['bad binding']);});
test('stale pose errors are ignored, current errors reject then recover on new pose',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);f.reply();f.bridge.pose('a',graph(2),head);f.reply(undefined,{ok:false,error:{message:'old failure'}});assert.equal(f.errors.length,0);f.reply(undefined,{ok:false,error:{message:'current failure'}});await assert.rejects(f.bridge.whenIdle(),/current failure/);f.bridge.pose('a',graph(3),head);f.reply();await f.bridge.whenIdle();assert.equal(f.meshes.length,1);});
test('worker crash and disposal reject waiters and never apply late geometry',async()=>{const f=fixture();f.bridge.bind('a',graph(0));const idle=f.bridge.whenIdle();f.crash();await assert.rejects(idle,/worker crash/);f.reply();assert.equal(f.meshes.length,0);const g=fixture();g.bridge.bind('b',graph(0));const pending=g.bridge.whenIdle();g.bridge.dispose();await assert.rejects(pending,/disposed/);g.reply();assert.equal(g.meshes.length,0);assert.equal(g.worker.terminated,true);});

test('a later pose after binding failure rejects instead of stranding the queue',async()=>{const f=fixture();f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(1),head);f.reply(undefined,{ok:false,error:{message:'bad binding'}});assert.throws(()=>f.bridge.pose('a',graph(2),head),/bad binding/);await assert.rejects(f.bridge.whenIdle(),/bad binding/);assert.equal(f.bridge.pending,false);f.bridge.bind('a',graph(0));f.bridge.pose('a',graph(2),head);f.reply();f.reply();f.reply();await f.bridge.whenIdle();assert.equal(f.meshes.length,1);});
