import test from 'node:test';
import assert from 'node:assert/strict';
import {SceneModel} from '../scene-state.js';
import {exportScene} from '../scene-file.js';
import {setupSceneFiles,MAX_ARCHIVE_BYTES,MAX_SOURCE_BYTES} from '../scene-files-ui.js';
const positions=[[0,.95,0],[0,1.35,0],[0,1.55,0],[0,1.72,0],[.32,1.4,0],[.58,1.2,0],[.79,1,0],[-.32,1.4,0],[-.58,1.2,0],[-.79,1,0],[.15,.85,0],[.15,.48,0],[.15,.08,.08],[-.15,.85,0],[-.15,.48,0],[-.15,.08,.08]];
const graph=()=>({nodes:positions.map((position,i)=>({position:[...position],radii:[.06,.06],root:i===0})),edges:[[0,1],[1,2],[2,3],[1,4],[4,5],[5,6],[1,7],[7,8],[8,9],[0,10],[10,11],[11,12],[0,13],[13,14],[14,15]].map(([a,b])=>({a,b}))});
class Element extends EventTarget{value='';files=[];clicks=0;click(){this.clicks++;this.dispatchEvent(new Event('click'));}}
const encode=text=>new TextEncoder().encode(text),decode=bytes=>new TextDecoder().decode(bytes);
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function fixture(options={}){const model=new SceneModel(graph()),saveButton=new Element(),openButton=new Element(),fileInput=new Element(),errors=[],downloads=[],changed=[];const ui=setupSceneFiles({model,saveButton,openButton,fileInput,archive:{encode,decode},onChange:()=>changed.push(model.state),onError:error=>errors.push(error.message),download:bytes=>downloads.push(bytes),...options});return {model,saveButton,openButton,fileInput,errors,downloads,changed,ui};}
function sceneFile(model){const bytes=encode(exportScene(model.state));return {size:bytes.byteLength,arrayBuffer:async()=>bytes.buffer};}
const nextTurn=()=>new Promise(r=>setImmediate(r));
test('save exports a source snapshot through archive encoder without changing history',async()=>{const f=fixture();f.model.dispatch({type:'add'});const before=f.model.state,revision=f.model.revision;assert.equal((await f.ui.save()).status,'saved');assert.equal(decode(f.downloads[0]),exportScene(before));assert.equal(f.model.revision,revision);assert.deepEqual(f.model.state,before);});
test('valid file atomically replaces the scene in a single undoable edit',async()=>{const f=fixture(),source=new SceneModel(graph());source.dispatch({type:'add'});const before=f.model.state;assert.equal((await f.ui.loadFile(sceneFile(source))).status,'loaded');assert.deepEqual(f.model.state.characters,source.state.characters);assert.equal(f.changed.length,1);f.model.undo();assert.deepEqual(f.model.state.characters,before.characters);assert.equal(f.model.state.selectedId,before.selectedId);});
test('no file and cancelled chooser leave scene, revision and history alone',async()=>{const f=fixture(),before=f.model.state,revision=f.model.revision;assert.equal((await f.ui.loadFile(null)).status,'cancelled');f.ui.open();f.fileInput.dispatchEvent(new Event('cancel'));assert.deepEqual(f.model.state,before);assert.equal(f.model.revision,revision);assert.equal(f.errors.length,0);});
test('oversized archive is rejected before reading and oversized decoded source before parsing',async()=>{let reads=0;const f=fixture({readBytes:async()=>{reads++;return new Uint8Array();}});const before=f.model.state;assert.equal((await f.ui.loadFile({size:MAX_ARCHIVE_BYTES+1})).status,'error');assert.equal(reads,0);const g=fixture({archive:{encode,decode:()=> 'é'.repeat(MAX_SOURCE_BYTES/2+1)}});assert.equal((await g.ui.loadFile({size:1,arrayBuffer:async()=>new ArrayBuffer(1)})).status,'error');assert.equal(g.changed.length,0);assert.deepEqual(f.model.state,before);});
test('invalid archive or scene preserves all current state',async()=>{const f=fixture({archive:{encode,decode:()=>{throw Error('Invalid SQLite');}}}),before=f.model.state;assert.equal((await f.ui.loadFile({size:1,arrayBuffer:async()=>new ArrayBuffer(1)})).status,'error');assert.deepEqual(f.model.state,before);const g=fixture();assert.equal((await g.ui.loadFile({size:1,arrayBuffer:async()=>encode('bad JSON').buffer})).status,'error');assert.equal(g.changed.length,0);});
test('edits while file bytes are loading prevent stale replacement',async()=>{const gate=deferred(),f=fixture({readBytes:()=>gate.promise}),file=sceneFile(f.model);const pending=f.ui.loadFile(file);f.model.dispatch({type:'color',id:f.model.state.selectedId,color:'#123456'});const edited=f.model.state;gate.resolve(await file.arrayBuffer());assert.equal((await pending).status,'error');assert.deepEqual(f.model.state,edited);assert.match(f.errors[0],/Scene changed/);});
test('edits during async archive decoding also prevent replacement',async()=>{const gate=deferred(),f=fixture({archive:{encode,decode:()=>gate.promise}}),file=sceneFile(f.model);const pending=f.ui.loadFile(file);await nextTurn();f.model.dispatch({type:'add'});const edited=f.model.state;gate.resolve(decode(new Uint8Array(await file.arrayBuffer())));assert.equal((await pending).status,'error');assert.deepEqual(f.model.state,edited);});
test('newer open supersedes an earlier asynchronous read without surfacing its error',async()=>{const gate=deferred(),f=fixture({readBytes:file=>file.slow?gate.promise:file.arrayBuffer()}),old=sceneFile(f.model);const pending=f.ui.loadFile({...old,slow:true});const source=new SceneModel(graph());source.dispatch({type:'add'});assert.equal((await f.ui.loadFile(sceneFile(source))).status,'loaded');gate.resolve(await old.arrayBuffer());assert.equal((await pending).status,'stale');assert.deepEqual(f.model.state.characters,source.state.characters);assert.equal(f.errors.length,0);});
test('revision is captured before chooser opens, and same filename selection resets',async()=>{let reads=0;const f=fixture({readBytes:file=>{reads++;return file.arrayBuffer();}}),file=sceneFile(f.model);f.ui.open();f.model.dispatch({type:'add'});f.fileInput.files=[file];f.fileInput.value='same.human.sqlite';f.fileInput.dispatchEvent(new Event('change'));await nextTurn();assert.equal(reads,0);assert.match(f.errors[0],/Scene changed/);assert.equal(f.fileInput.value,'');f.ui.open();f.fileInput.files=[file];f.fileInput.value='same.human.sqlite';f.fileInput.dispatchEvent(new Event('change'));await nextTurn();assert.equal(reads,1);assert.equal(f.fileInput.value,'');assert.equal(f.changed.length,1);});
test('active gesture import is rejected without cancelling or committing it',async()=>{const f=fixture(),file=sceneFile(f.model);f.model.beginGesture();const before=f.model.state,revision=f.model.revision;assert.equal((await f.ui.loadFile(file)).status,'error');assert.equal(f.model.gestureActive,true);assert.equal(f.model.revision,revision);assert.deepEqual(f.model.state,before);});
test('cancelled newer chooser invalidates old read and disposal ignores late results',async()=>{const gate=deferred(),f=fixture({readBytes:()=>gate.promise}),file=sceneFile(f.model);const pending=f.ui.loadFile(file);f.ui.open();f.fileInput.dispatchEvent(new Event('cancel'));gate.resolve(await file.arrayBuffer());assert.equal((await pending).status,'stale');assert.equal(f.changed.length,0);const next=deferred(),g=fixture({readBytes:()=>next.promise});const read=g.ui.loadFile(file);g.ui.dispose();next.resolve(await file.arrayBuffer());assert.equal((await read).status,'stale');g.openButton.click();assert.equal(g.fileInput.clicks,0);assert.equal(g.changed.length,0);});
