from pathlib import Path
import argparse,hashlib,json,html,shutil,subprocess
SOURCE=Path(__file__).resolve().parent
parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,required=True);parser.add_argument('--proof-receipt',type=Path,required=True);parser.add_argument('--model-audit',type=Path,required=True);args=parser.parse_args()
args.output.mkdir(parents=True,exist_ok=True)
template=(SOURCE/'index.template.html').read_text();model=(SOURCE/'model.mjs').read_text()
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=SOURCE,text=True).strip()
proof=json.loads(args.proof_receipt.read_text());audit=json.loads(args.model_audit.read_text());claims=json.loads((SOURCE/'claims.json').read_text())
assert proof['result']=='PASS_SIX_FRESH_REAL_CONTRACTS' and proof['sourceHead']==head
assert proof['sourceSha256']==sha(SOURCE/'NonuniformIsochoric.lean') and proof['claimsSha256']==sha(SOURCE/'claims.json') and proof['checkerSha256']==sha(SOURCE/'check_proofs.py')
assert len(proof['claims'])==len(claims)==6
for actual,claim in zip(proof['claims'],claims,strict=True):
 assert all(actual.get(k)==v for k,v in claim.items()) and actual['status']=='checked' and set(actual['axioms'])<={'propext','Quot.sound','Classical.choice'}
assert audit['result']=='PASS_SEPARATE_SYMBOLIC_GEOMETRY_TOPOLOGY_AND_TEXT_AUDIT'
assert audit['sourceHashes']=={name:sha(SOURCE/name) for name in ['model.mjs','index.template.html','model_audit.py']}
for source,name in [(SOURCE/'NonuniformIsochoric.lean','NonuniformIsochoric.lean'),(SOURCE/'claims.json','claims.json'),(args.proof_receipt,'nonuniform-proof-status.json'),(args.proof_receipt.parent/'nonuniform-lean-check.txt','nonuniform-lean-check.txt'),(args.model_audit,'model-audit.json')]:shutil.copyfile(source,args.output/name)
cards=''.join('<article class="real-contract" id="'+c['id']+'"><h3>'+html.escape(c['theorem'])+'</h3><p>'+html.escape(c['statement'])+'</p><pre class="lean-statement">'+html.escape(c['statement_lean'])+'</pre><p>'+html.escape(c['limitations'])+'</p></article>' for c in claims)
proofContent='<section class="panel" id="real-contracts"><h2>Six freshly checked Real contracts</h2><p>Lean checks the declared matrix determinant, positive interval stretch and an algebraic straight-cell error formula. The derivative, change-of-variables argument, mesh topology and floating-point implementation are separate audit obligations. The existing book remains at 103 claims; this extension is not registered pending independent acceptance.</p><p class="downloads"><a href="NonuniformIsochoric.lean" data-print-target="full-lean-source">Download complete Lean source</a> · <a href="claims.json" data-print-target="real-contracts">Exact statement inventory</a> · <a href="nonuniform-proof-status.json" data-print-target="kernel-receipt">Source-bound check receipt</a> · <a href="nonuniform-lean-check.txt" data-print-target="kernel-check">Kernel dependency report</a> · <a href="model-audit.json" data-print-target="model-audit">Separate model audit</a></p>'+cards+'</section><section class="panel" id="full-lean-source"><h2>Complete checked Lean source</h2><pre>'+html.escape((SOURCE/'NonuniformIsochoric.lean').read_text())+'</pre></section><section class="panel" id="kernel-receipt"><h2>Exact source and toolchain</h2><p>Source revision '+head+'</p><p>'+html.escape(proof['leanVersion'])+'</p><p>Source SHA-256 '+proof['sourceSha256']+'</p><p>Claim-map SHA-256 '+proof['claimsSha256']+'</p></section><section class="panel" id="kernel-check"><h2>Kernel dependency report</h2><pre>'+html.escape((args.proof_receipt.parent/'nonuniform-lean-check.txt').read_text())+'</pre></section><section class="panel" id="model-audit"><h2>Separate model and geometry audit</h2><p>Symbolic differentiation recovers every entry of the declared gradient. Ninety parameter/refinement cases compare closed oriented meshes against high-precision boundary volumes and an independent regular-polygon/frustum route. Surface topology and nondegenerate faces are checked separately.</p><p>Independent peer acceptance is pending. These routes do not prove force equilibrium, a muscle law or anatomical completion.</p><pre>'+html.escape(json.dumps(audit['numericalChecks'],indent=2))+'</pre></section>'
assert template.count('__MODEL_CODE__')==1
assert template.count('__PROOF_CONTENT__')==1
target=args.output/'nonuniform-volume-lab.html';target.write_text(template.replace('__MODEL_CODE__',model).replace('__PROOF_CONTENT__',proofContent))
receipt={'kind':'SELF_CONTAINED_STANDALONE_PROPERTY_LAB_WITH_CHECKED_REAL_CONTRACTS','sourceHead':head,'formalProofRegistration':'NOT_REGISTERED_PENDING_INDEPENDENT_ACCEPTANCE','standaloneCheckedRealContracts':6,'proofReceiptSha256':sha(args.proof_receipt),'modelAuditSha256':sha(args.model_audit),'inputs':{p.name:sha(p) for p in [SOURCE/'model.mjs',SOURCE/'index.template.html',SOURCE/'NonuniformIsochoric.lean',SOURCE/'claims.json',SOURCE/'check_proofs.py',SOURCE/'model_audit.py',Path(__file__)]},'output':{'name':target.name,'sha256':sha(target),'bytes':target.stat().st_size}}
(args.output/'build-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(target)
