import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {DEFAULTS,solveComparison,SCOPE} from './model.mjs';import {sceneMarkup} from '../directional-compression-lab/view.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../..'),args=process.argv.slice(2),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
if(args.length!==4||args[0]!=='--out'||args[2]!=='--proof')throw Error('Use --out ABSOLUTE_NEW_DIRECTORY --proof ABSOLUTE_ACCEPTED_PASSIVE_RECEIPT');
const out=args[1],proof=args[3];if(!path.isAbsolute(out)||!path.isAbsolute(proof)||fs.existsSync(out))throw Error('Fresh external output required');
const lock=JSON.parse(fs.readFileSync(path.join(here,'inputs.lock.json')));for(const f of lock.files){const b=fs.readFileSync(path.join(repo,f.path));if(b.length!==f.bytes||sha(b)!==f.sha256)throw Error('Reviewed passive source mismatch: '+f.path);}
// The unchanged accepted builder validates all original source/proof bindings.
const built=spawnSync(process.execPath,[path.join(here,'../directional-compression-lab/build.mjs'),...args],{encoding:'utf8'});if(built.status!==0)throw Error(built.stderr||built.stdout);
fs.renameSync(path.join(out,'README.md'),path.join(out,'inherited-passive-method.md'));fs.copyFileSync(path.join(here,'README.md'),path.join(out,'README.md'));
for(const name of ['model.mjs','app.mjs']){const dest=path.join(out,'education/contributions/full-face-load-pressure',name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(here,name),dest);}
const initial=solveComparison(),escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),source=fs.readFileSync(path.join(out,'AreaLoadContracts.lean'),'utf8');
const fields=[['axialStretch','Prescribed X stretch',.8,1.2,.01],['breadthFactor','Free-axis reference breadth factor',.5,2,.1],['forceN','Total one-face compressive force (N)',0,100,.01],['pressurePa','Current-area applied traction (Pa)',0,100000,50],['mu','Shear parameter mu (Pa)',500,5000,100],['bulk','Bulk parameter K (Pa)',0,250000,500]];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Full-face load versus pressure</title><link rel="stylesheet" href="style.css"></head><body><header><p>Kenoma · standalone passive inverse loading</p><h1>Hold total force or current-area pressure</h1><p>The same elastic specimen law, with actual transverse equilibrium solves.</p></header><main><p class="notice"><strong>AUTHORED · UNCALIBRATED · PASSIVE · FULL FACE.</strong> Changing reference breadth changes material amount. This does not vary a contact patch on a fixed body.</p><div class="controls"><label>Loading mode<select data-param="mode"><option value="force">Fixed total force</option><option value="pressure">Fixed current pressure</option></select></label><label>Loaded transverse axis<select data-param="direction"><option>Y</option><option>Z</option></select></label>${fields.map(([key,label,min,max,step])=>`<label>${label}<input data-param="${key}" type="number" value="${DEFAULTS[key]}" min="${min}" max="${max}" step="${step}"></label>`).join('')}<label>Outer solve cap<select data-param="outerIterations"><option>8</option><option>32</option><option selected>64</option></select></label></div><button id="reset">Reset</button><button id="export">Download displayed state</button><p role="status" id="status">Static default below; source checks enable the controls.</p><div id="scene">${sceneMarkup(initial.state)}</div><dl id="readout"><div><dt>Default stretches X/Y/Z</dt><dd>${initial.state.stretches.join(' / ')}</dd></div><div><dt>Default C (N) and q (Pa)</dt><dd>${initial.state.compressionResultantN} / ${initial.state.contactPressurePa}</dd></div></dl><noscript>JavaScript is disabled; solved default, definitions and complete source remain readable.</noscript></main><section id="equations"><h2>Force, pressure and reference geometry</h2><pre>U = V0 [mu/2 (J^(-2/3) I1 - 3) + K/2 (J - 1)^2]
Pi = mu J^(-2/3) (li - I1/(3 li)) + K (J - 1) J/li
J = lx ly lz; I1 = lx² + ly² + lz²
C = -Pload A0; Acurrent = A0 lx b
q = C/Acurrent = -sigma_load; Nx = Px H0 D0</pre><p>C and q are compression positive on one loaded face. Nx is tension positive. Nominal compression is C/A0. Current area is geometric full-face area, not PCSA. Applied normal traction and solid stress are not fluid pressure.</p><p>For reference X/Y/Z = 0.08/0.06/0.05 m, breadth scales the free-axis reference dimension. It changes A0, reference volume and end area. At fixed pressure the constitutive state is independent of breadth, while force and energy scale with material amount. At fixed force, the solved state changes. The displayed end stress separates geometry from the end resultant.</p><p>${escape(SCOPE)}</p><h2>Two equations, two transverse unknowns</h2><p>Fix lx in 0.8..1.2. Solve b from Pfree=0 using the accepted 64-step inner solve and 1e-5 Pa residual. Solve h in 0.5..1 from C=Ctarget or q=qtarget, using 8/32/64 outer bisections. Outer criteria are 1e-8 N or 1e-5 Pa. Both must pass; eight steps can fail.</p><p>Signed bracketing selects a root without imposing a force direction. Unbracketed targets are refused; endpoint values do not establish the full attainable range or global uniqueness. No stability or biological agreement follows from the residual.</p><p>These are bilateral loading grips and free remaining faces, with nonnegative compression targets. No unilateral contact or friction is modeled. Fixed current pressure is a follower surface traction: adding qV to the energy would incorrectly also load the intended free faces.</p><p><a href="README.md">Download full method</a> · <a href="AreaLoadContracts.lean">Download inherited exact Lean source</a> · <a href="proof-receipt.json">Download inherited proof receipt</a></p></section><section id="proof-source"><h2>Complete inherited conditional source</h2><p>Three accepted unregistered Std identities, with explicit algebraic assumptions. No new declarations. No Real instantiation, energy derivative, equilibrium algorithm or biological theorem. Registered ordinary proof status remains 30 passed / 85 unrun.</p><pre class="proof-source">${escape(source)}</pre></section><script type="module" src="boot.mjs"></script></body></html>`;
fs.writeFileSync(path.join(out,'index.html'),html.replaceAll('<input ','<input disabled ').replaceAll('<select ','<select disabled ').replaceAll('<button ','<button disabled '));
fs.copyFileSync(path.join(here,'boot.mjs'),path.join(out,'boot.mjs'));fs.writeFileSync(path.join(out,'default-state.json'),JSON.stringify(initial,null,2)+'\n');fs.copyFileSync(path.join(here,'inputs.lock.json'),path.join(out,'successor-inputs.lock.json'));
const paths=['index.html','style.css','README.md','AreaLoadContracts.lean','proof-receipt.json','inherited-passive-method.md',...['app','model','view'].map(n=>'education/contributions/directional-compression-lab/'+n+'.mjs'),...['app','model'].map(n=>'education/contributions/full-face-load-pressure/'+n+'.mjs'),...['continuum-properties','material-response','tissue','property-labs','tapered-bar'].map(n=>'education/web/'+n+'.mjs')];
fs.writeFileSync(path.join(out,'runtime-integrity.json'),JSON.stringify({schema:1,files:paths.map(name=>{const b=fs.readFileSync(path.join(out,name));return {path:name,bytes:b.length,sha256:sha(b)};})},null,2)+'\n');console.log(JSON.stringify({result:'PASS_SOURCE_BOUND_FULL_FACE_LOAD_PRESSURE',runtimeFiles:paths.length,default:initial.state.stretches,converged:initial.solve.converged,newLeanDeclarations:0}));
