import pathlib,json,hashlib,subprocess
repo=pathlib.Path('/workspace/Kenoma-patch-runner');root=repo/'education';prefdir=root/'review/selective-fixed-patch-preflight-20261007';read=lambda p:json.loads(p.read_text());digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
pref=read(prefdir/'preflight.json');geometry=read(pathlib.Path('/tmp/selective-independent-structural.json'));nonzero=read(pathlib.Path('/tmp/selective-independent-nonzero.json'));replay=read(pathlib.Path('/tmp/selective-independent-nonzero-replay.json'));envelopes=read(pathlib.Path('/tmp/selective-independent-envelopes.json'))
assert pref['sourceCommit']==geometry['sourceCommit']=='0582de9d86d75ccbb7cc61c74d2c88e320f675af';assert digest(prefdir/'preflight.json')=='2c6a8c69765f57408860f433379b68595b2a4a55aabb2238205ddcb6b86912bb';assert pref['tests']['pass']==50 and pref['specimenCalls']==pref['materialLawInvocations']==0
assert subprocess.check_output(['git','status','--porcelain'],cwd=repo,text=True)==''
assert not (root/'research/selective-fixed-patch-authorization-20261007.json').exists();assert not (root/'review/selective-fixed-patch-run-20261007').exists()
for p in ['tools/selective-fixed-patch-protocol.mjs','tools/selective-fixed-patch-runtime.mjs','tools/selective-fixed-patch-storage.mjs','tools/selective-fixed-patch-inputs.mjs','tools/fixed-field-integration-assembly.mjs','tools/isolated-collapse-components.mjs','web/anatomical-material.mjs']:
 assert subprocess.check_output(['git','show','a36f676c74374c2b4a757748b13e06b34345ea1e:education/'+p],cwd=repo)==subprocess.check_output(['git','show',pref['sourceCommit']+':education/'+p],cwd=repo)
mat=pathlib.Path(nonzero['outputDirectory'])/'material';inventory={'schema':1,'scope':'Independent structural synthetic constant callback evidence only; no actual material evaluation or operational execution','specimenCalls':0,'syntheticCallbacks':497500,'files':{p.name:{'bytes':p.stat().st_size,'sha256':digest(p)} for p in sorted(mat.iterdir())}}
invpath=pathlib.Path('/tmp/selective-independent-synthetic-inventory.json');invpath.write_text(json.dumps(inventory,indent=2)+'\n');assert len(inventory['files'])==1229
paths=['/tmp/review_selective_structural.py','/tmp/review_selective_nonzero.mjs','/tmp/review_selective_nonzero_replay.py','/tmp/review_selective_envelopes.mjs','/tmp/assemble_selective_independent_report.py','/tmp/selective-independent-structural.json','/tmp/selective-independent-final-structural.log','/tmp/selective-independent-js.log','/tmp/selective-independent-final-lifetime.log','/tmp/selective-independent-final-verifier.log','/tmp/selective-independent-authorization-refusal.log','/tmp/selective-independent-nonzero.json','/tmp/selective-independent-nonzero.log','/tmp/selective-independent-nonzero-replay.json','/tmp/selective-independent-nonzero-replay.log','/tmp/selective-independent-envelopes.json','/tmp/selective-independent-envelopes.log',str(invpath)]
report={'schema':1,'verdict':'PASS','scope':'Independent structural preflight and resource-accounting review only; execution not authorized','sourceCommit':pref['sourceCommit'],'preflightEvidenceCommit':'6d3851e7f625baae2e94ebea4261eb852691420d','baseCommit':'98905757dd9cac78cb9c1168e7039aa091e6eb33','preflightSha256':digest(prefdir/'preflight.json'),'storagePlanSha256':digest(prefdir/'storage-plan.json'),'specimenCalls':0,'materialLawInvocations':0,'executionAuthorized':False,'newOperationalExecution':False,'newNumericalAgreementClaim':False,'anatomicalQualification':False,'blockingFindings':[],
'geometryIndependentReplay':geometry['checks'],'syntheticNonzeroProducerBoundary':nonzero,'independentNonzeroRegionAndComparisonReplay':replay,'worstNumericTokenEnvelopes':envelopes,'tests':{'independentlyRerunJS':8,'acceptedLifetime':30,'newVerifierAndDamage':11,'missingNewAuthorizationRefusal':1,'total':50,'fail':0},
'correctedFindings':[{'finding':'execute.log64KiB envelope originally unenforced','resolution':'Optional scope-specific execute_log_cap_bytes propagated supervisor/private-worker/child, new launcher65536; defaults preserve historical behavior; synthetic65537-byte output refuses/cleans up.'},{'finding':'output hash inventory could omit expected entries','resolution':'Exact plan-file set excluding self completion/terminal now required, positive and subset damage tests pass.'},{'finding':'current source hash could replace frozen preflight source anchor','resolution':'Every preflight source hash must equal completion source hash, independently of current disk verification; anchor damage test passes.'}],
'reviewedProperties':['497500 new callbacks maximum/planned;4000 accepted reused measurements separate;634logicalregions; no retry','All16patch elements and585nodes includingheld;252oldU3rows replayed;236outside unchanged/unqualified','All4secondarycorner mappings and X44face231; dyadic disjoint coverage; no current-J physical-weight multiplier','RequiredQ0/Q1=156units,Q1/Q2=36,F44/R44=21;Q0/Q2informational; oldD5secondary contributes wholeelement only','Every5-term comparison uses signed+unittriangle force1e-5N andwork5.492029235357012e-7J; reconstruction1e-8N/1e-9J','Finite JSON/closed paths/actual perfile encoding caps; exact12782000Bbinary, maximumcombined48925104B<67108864B','Callback entered/completed/reserved failure counters preserved; partial weights durable/bounded; refusal/cleanup/pending/final/laterfailure precedence retained','Newscope/parentthread/source/preflight/review/budget one-shot authorization required; missingauth refuses before Node/run; oldexit1 and consumed authorization unchanged'],
'limitations':['Structural success gives no result of actual specimen integration. Synthetic callback counts are explicitly distinct from zero material-law invocations.','300s is a proposed authorized future cap, not a timing guarantee for actual material execution.','Finite comparisons do not give analytic integration error/continuum/equilibrium/tangent/displacement/anatomical qualification.','Within-unit cancellation remains possible; saved-direction work follows the force bound algebraically.','No new authorization, run, publication, branch changes, deployment, protection or credential writes by this reviewer.','Full synthetic raw1229files retained only in temporary outputDirectory; independent inventory binds their exact bytes.'],
'artifacts':{p:{'bytes':pathlib.Path(p).stat().st_size,'sha256':digest(pathlib.Path(p))} for p in paths}}
out=pathlib.Path('/tmp/selective-independent-review.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'verdict':report['verdict'],'sourceCommit':report['sourceCommit'],'preflightSha256':report['preflightSha256'],'report':str(out),'sha256':digest(out),'bytes':out.stat().st_size,'supportArtifacts':len(paths),'syntheticRawFiles':1229},indent=2))
