import fs from 'node:fs';import assert from 'node:assert/strict';import path from 'node:path';
const R='/workspace/Kenoma-patch-runner/education/tools/';
const P=await import(R+'selective-fixed-patch-protocol.mjs'),I=await import(R+'selective-fixed-patch-inputs.mjs'),S=await import(R+'selective-fixed-patch-storage.mjs'),A=await import(R+'selective-fixed-patch-runtime.mjs'),T=await import(R+'element247-shell-runtime.mjs'),H=await import(R+'element247-shell-protocol.mjs');
const out=fs.mkdtempSync('/tmp/selective-independent-full-nonzero-'),store=new S.PatchEvidenceStore(out),pref=I.read(I.PREF+'preflight.json'),{source,arrays}=I.loadInputs(),limits=new T.RuntimeLimits({plannedCalls:497500,maximumCalls:497500,wallMs:300000,rssBytes:2147483648}),context={reusedPoints:0,completedRegions:[],partialRegion:null},maxima={};let callbacks=0;
const callback=()=>{callbacks++;const v=[2,-1,3,4,1,-2,5,-3,6];return {actual:{J:1,P:v.map(x=>10*x),energy:Object.fromEntries(P.ALL_TERMS.slice(0,-1).map((t,i)=>[t,7*(i+1)]))},stresses:Object.fromEntries(P.ALL_TERMS.slice(0,-1).map((t,i)=>[t,v.map(x=>(i+1)*x)]))};};
for(const [name] of Object.entries(store.plan.files).filter(([n])=>n.endsWith('-points.f64le')))store.write(name,I.bytes(I.PREF+name));
store.write('saved-arrays.json',I.bytes(I.OLD+'saved-arrays.json'));
for(const state of P.STATES){const stages={};for(const r of P.SCHEDULE){const reusedRows=state==='terminal46'&&r.id==='F44'?Object.fromEntries(H.shells(20).slice(0,2).map(s=>[s.id,P.regionRow(I.read(I.FAILED+`T24-terminal46-${s.id}-shell.json`),r,s)])):{};stages[`${r.element}-${r.id}`]=A.assembleStage({source,r,state,positions:arrays.positionsM[state],direction:arrays.terminalDirectionM,limits,store,materialCallback:callback,context,preflight:pref,readArtifact:n=>I.bytes(I.PREF+n),reusedRows});}
 const base=I.baselineFor(source,state),candidates={};for(const q of ['Q0','Q1','Q2']){candidates[q]=I.assembleCandidate(source,state,q,stages,base);store.json(`${state}-${q}-hybrid.json`,candidates[q]);}
 for(const [a,b] of [['Q0','Q1'],['Q1','Q2'],['Q0','Q2']])store.json(`${state}-${a}-${b}-comparison.json`,I.candidateComparison(source,state,a,b,candidates,stages,arrays.terminalDirectionM));store.json(`${state}-F44-R44-comparison.json`,I.radialComparison(source,state,stages,arrays.terminalDirectionM));}
limits.finish();assert.equal(callbacks,497500);assert.equal(context.reusedPoints,4000);assert.equal(context.completedRegions.length,634);
for(const [name,record] of Object.entries(store.files)){const type=name.endsWith('-region.json')?'region':name.endsWith('-stage.json')?'stage':name.endsWith('-hybrid.json')?'hybrid':name.endsWith('-comparison.json')?'comparison':name.endsWith('.f64le')?'binary':'saved';maxima[type]=Math.max(maxima[type]??0,record.bytes);}
const report={verdict:'PASS_SYNTHETIC_NONZERO_FULL_OUTPUT_SHAPES',specimenCalls:0,syntheticCallbacks:callbacks,reusedMeasurements:context.reusedPoints,serializedRegions:context.completedRegions.length,allCornerMappings:true,allFiveRules:true,bothFields:true,full16Hybrids:6,comparisons:8,outputDirectory:out,maximumEncodedBytesByType:maxima,outputBytes:T.treeBytes(out),counts:limits.receipt()};fs.writeFileSync('/tmp/selective-independent-nonzero.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
