#!/usr/bin/env python3
"""Exact frozen JSON audit: retained evidence and symbolic arithmetic only."""
import json,pathlib,hashlib,subprocess,math
ROOT=pathlib.Path('/tmp/Kenoma-fine-window-outcome-review');OUT=pathlib.Path('/tmp/fine-window-targeted-proposal-independent');PIN='0c87557f783cc08c1d5c75640e4a9bf1eb7f521d';SHA='939ce954145302b0b941826d65763530cbbae8fd72cdc2ad2f3a2eaef79977c2';P=ROOT/'education/research/fine-window-targeted-witness-proposal-20261007.json';checks=0

def eq(a,b):
 global checks
 assert a==b,(a,b);checks+=1

def ok(v):
 global checks
 assert v;checks+=1

b=P.read_bytes();eq(hashlib.sha256(b).hexdigest(),SHA);eq(subprocess.check_output(['git','-C',str(ROOT),'rev-parse','HEAD'],text=True).strip(),PIN);eq(subprocess.check_output(['git','-C',str(ROOT),'show',PIN+':education/research/fine-window-targeted-witness-proposal-20261007.json']),b);eq(subprocess.check_output(['git','-C',str(ROOT),'status','--porcelain'],text=True),'')
p=json.loads(b);old='5f7612f6c7f6609d8946b3394d7363609d7a30b1';eq(p['frozenCompletedResultCommit'],old)
for path,key in [('education/research/fine-window-authorization-20261007.json','consumedAuthorizationSha256'),('education/review/fine-window-outcome-20261007/raw-inventory.json',None)]:
 raw=(ROOT/path).read_bytes();eq(subprocess.check_output(['git','-C',str(ROOT),'show',old+':'+path]),raw);eq(hashlib.sha256(raw).hexdigest(),p[key] if key else p['retainedDataReferences']['rawInventorySha256'])
eq(p['states'],['control45','terminal46']);eq(p['terms'],['matrix','volume','passiveFiber','activePotential','total']);eq(len(p['patch']),16);eq(len(set(p['patch'])),16);eq(sorted(p['focus']+p['quiet']),p['patch']);eq(len(p['focus']),7);eq(len(p['quiet']),9)
selection=[[247,'s1'],[247,'s2'],[247,'s3'],[206,'s1']];eq(p['selectedRegions'],selection);r=p['proposedNewRule'];eq(r['gaussOrder'],5);eq(r['depth'],20);eq(r['faceParts'],16);eq(r['radialParts'],2);eq(r['corners'],{'247':0,'206':1});eq(r['shells'],{'s1':[.5,1],'s2':[.25,.5],'s3':[.125,.25]});eq(r['tetrahedraPerSelectedShell'],3*2*16**2);points=3*2*16**2*5**3;eq(r['pointsPerSelectedShellPerField'],points);eq(p['newPlannedAndMaximumCallbacks'],4*points*2);eq(p['newNormalizedBinaryBytes'],4*points*48);eq(p['newPhysicalWeightBinaryBytes'],4*points*8);eq(p['newBinaryBytes'],4*points*56)
eq(p['endpoints'],{'T0':{'quiet':'immutable U4','selectedFocusRegions':'completed I1','unselectedFocusRegions':'completed I0'},'T1':{'quiet':'immutable U5','selectedFocusRegions':'prospective new I2','unselectedFocusRegions':'completed I1'}})
eq(p['requiredFutureComparisons'],[{'a':'T0','b':'T1','partition':156,'allocation':'unchanged85percentquiet15percentfocus'},{'a':'S2','b':'T1','partition':156,'allocation':'unchanged20percentquiet80percentfocus'}]);eq(9+7*21,156);eq(p['all585IncludingHeld'],True)
g=p['gates'];eq(g['globalForceN'],1e-5);eq(g['globalWorkJ'],5.492029235357012e-7)
for prefix,quiet,focus in [('independent',.85,.15),('crossFamily',.2,.8)]:
 for subset,fraction in [('Quiet',quiet),('Focus',focus)]:
  ok(math.isclose(g[prefix+subset+'ForceN'],fraction*g['globalForceN'],rel_tol=0,abs_tol=2e-21));ok(math.isclose(g[prefix+subset+'WorkJ'],fraction*g['globalWorkJ'],rel_tol=0,abs_tol=2e-22))
for k,v in [('reconstructionForceN',1e-8),('reconstructionEnergyJ',1e-9),('physicalStationarityN',1e-4),('sampleJStrictlyGreaterThan',1e-6)]:eq(g[k],v)
d=json.loads((ROOT/'education/review/fine-window-completed-review-20261007/localization/design-check.json').read_text());four=d['options']['four'];five=d['options']['five'];eq(p['retainedComplementMaximumForceN'],four['retainedComplementMaximumForceN']);eq(p['retainedComplementMaximumWorkJ'],four['retainedComplementMaximumWorkJ']);eq(p['conservativeAvailableFocusForceForSelectedIncrementN'],g['independentFocusForceN']-p['retainedComplementMaximumForceN']);eq(p['conservativeAvailableFocusWorkForSelectedIncrementJ'],g['independentFocusWorkJ']-p['retainedComplementMaximumWorkJ']);ok(p['conservativeAvailableFocusForceForSelectedIncrementN']<1.2e-8);eq(p['expectedPassClaim'],False)
m=p['moreHeadroomOption'];eq(m['addRegion'],[247,'s4']);eq(m['newPlannedAndMaximumCallbacks'],5*points*2);eq(m['newBinaryBytes'],5*points*56);eq(m['retainedComplementMaximumForceN'],five['retainedComplementMaximumForceN']);eq(m['conservativeFocusHeadroomN'],five['availableFocusForceForNewIncrementN']);eq(m['requiresProspectiveChoice'],True);eq(m['automaticExtensionOrRetryAuthorized'],False)
ok(d['threeRegionComplementLowerBoundN']>g['independentFocusForceN']);eq(d['minimumRegionalCountForOldComplementToFitFocusForce'],4);ok('No absoluteglobalminimumclaim' in p['minimumClaim']);ok('not an addedacceptancegate' in p['acceptanceUsesActualCombinedVectors'])
s=p['paperStorageSlotPlan'];eq(s['newBinaryChunks'],4*4*2);eq(s['newRegionJson'],4*2);eq(s['compositeStages'],4);eq(s['new16ElementHybrids'],4);eq(s['newComparisonsBothStates'],6);ok('UNVERIFIED' in s['status']);eq(points//4,48000);eq(48000*8,384000);ok(48000*8<=512*1024)
extra=sum(s[k] for k in ['startAndCompletionSlotsBytes','provenanceSlotBytes','savedArraysSlotBytes','terminalSlotBytes','externalSlotsBytes','emergencyBytes']);expected=4*points*56+8*8192+4*131072+4*1048576+6*2097152+extra;eq(s['fourRegionTotalEnvelopeBytes'],expected);eq(expected,69566464);five_expected=5*points*56+10*8192+4*131072+4*1048576+6*2097152+extra;eq(s['fiveRegionTotalEnvelopeBytes'],five_expected);eq(five_expected,80334848)
for k in ['newMaterialCallsDuringReview']:eq(p[k],0)
for k in ['newQuadratureGenerated','newRunnerImplemented','newExecutionAuthorized','outside236Qualified','anatomicalCapstoneQualified']:eq(p[k],False)
eq(p['noConvergenceProof'],True);eq(p['resultPreserved'],'UNRESOLVED_FIXED_PATCH_INTEGRATION');eq(p['proposedFutureBudget']['status'],'NOT_AUTHORIZED');eq(p['proposedFutureBudget']['plannedMaterialCalls'],1536000);eq(p['proposedFutureBudget']['maximumMaterialCalls'],1536000);eq(p['proposedFutureBudget']['retries'],0)
# Counts for the prospectively composed stage shapes are arithmetic, not generator calls.
shape={'T0-247':122000+3*(48000-6000),'T1-247':968000+3*(192000-48000),'T0-206':122000+(48000-6000),'T1-206':968000+(192000-48000)};eq(shape['T1-247'],1400000);eq(shape['T1-206'],1112000);eq(len(p['futureStructuralRequirements']),6);ok('perregion coverage' in p['futureStructuralRequirements'][1]);ok('durable completedchunkinventory' in p['futureStructuralRequirements'][2]);ok('representation bound' in p['futureStructuralRequirements'][3]);ok('freshsourceboundstructuralpreflight' in p['futureStructuralRequirements'][4])
report={'verdict':'PASS_SYMBOLIC_PROPOSAL_ONLY_CONDITIONAL_ON_FUTURE_STRUCTURAL_REVIEW','proposalCommit':PIN,'proposalSha256':SHA,'completedResultPreserved':old,'assertionsPassed':checks,'specimenCalls':0,'quadratureGenerated':False,'sourceMutations':False,'rejectedProseIssues':[],'exactCost':{'newCalls':1536000,'newBinaryBytes':43008000,'paperOutputEnvelopeBytes':expected,'paperEnvelopeEnforcedOrVerified':False},'optionalFiveRegionCost':{'newCalls':1920000,'newBinaryBytes':53760000,'paperOutputEnvelopeBytes':five_expected},'compositeStagePointCounts':shape,'limits':['Minimum physical-region count only within specified common m16/r2 and retained-complement class.','Only1.158108016577515e-8 N conservative new-increment headroom; no expected pass or new acceptance gate.','Four stage slots are paper assumptions: future production closure must prove complete serialized T0/T1 provenance/reductions fit, including larger composite point counts.','32/40binarychunk plan needs genuine streamed source-bound generation, positivity/coverage/moments, chunk-hash and reduction checks, durable completed/current-partial evidence and damage tests.','Original failed run remains unresolved; proposal is not preparation/execution authorization.','Outside236 and anatomical capstone remain unqualified.']}
(OUT/'review.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
